### ISSUE TITLE
Needs a transpiled distribution version of js

### ISSUE THREAD

**Issue by fotomut** [scniro/react-codemirror2#1]
Thanks for passing along this wrapper! 
We don't typically transpile our `node_modules` folder. Could you create a transpiled version of the component for distribution?

**Comment by scniro** [comment]
@fotomut hey! Thanks for opening up an issue to track. I just threw up the quickest MVP wrapper I could and hoped I could gain some interest and the issues/requests came rolling in. I intend to comb through the original react-codemirror [issue tracker](https://github.com/JedWatson/react-codemirror/issues) for getting ahead of the bend a bit.

Regarding this, could you please elaborate slightly more? Does your need regard the consumption of `.jsx` files? Would you be expecting to consume some distributed `.js` file for this? If so, what does that look like?

**Comment by fotomut** [comment]
@scniro Yes, we will need to consume a `.js` file that is in ES5. We have `.jsx` files, but they are in our project directories and are the only things that we are transpiling.

**Comment by scniro** [comment]
@fotomut  you got it 👍. Will keep you posted.

**Comment by scniro** [comment]
Hey again. [0.0.2](https://github.com/scniro/react-codemirror2/releases/tag/0.0.2) pushed up. Could you let me know if this is what you were needing? Also if you use codemirror a lot please, feel free to keep feeding suggestions for this wrapper component. I just started using codemirror so I wouldn't quite consider myself a power user quite yet. Unsure of all the cases where one would want some functionality at this moment. Surely I'll find them as I use it, but if you have any "must-haves" - sharing them would be super appreciated. Thanks!
