### ISSUE TITLE
Help: JSONLint not working 

### ISSUE THREAD

**Issue by nakkeeran** [scniro/react-codemirror2#10]
Hi,
Trying to make JSONLinting work for react-codemirror2.
Looks like im missing something here. 

Code - Imports
```
import CodeMirror from 'react-codemirror2'
import 'codemirror/lib/codemirror.css'
import 'codemirror/addon/lint/lint.css'
import 'codemirror/theme/material.css'

import 'codemirror/lib/codemirror'
import 'codemirror/mode/javascript/javascript'
import jsonlint from 'jsonlint/lib/jsonlint'
import 'codemirror/addon/lint/lint'
import 'codemirror/addon/lint/json-lint'

window.jsonlint = jsonlint
```
Component
```
render () {
    const codeMirrorOptions = {
      lineNumbers: true,
      mode: 'application/json',
      lint: true,
      gutters: ['CodeMirror-lint-markers'],
      theme: 'material'
    }

   const value = {
      name: 'Hello'
   }

    return (
      <CodeMirror
        value={value}
        options={codeMirrorOptions}
      />
    )
  }
```

No error on browser console, but lint is not working. :( 

<img width="638" alt="screen shot 2017-09-15 at 5 00 53 pm" src="https://user-images.githubusercontent.com/524846/30507258-7dcdf16c-9a37-11e7-964f-eadaa8471dd8.png">
 
Expected
<img width="498" alt="screen shot 2017-09-16 at 11 10 18 am" src="https://user-images.githubusercontent.com/524846/30514735-d11b23f6-9acf-11e7-939d-1420e872abf1.png">

**Comment by scniro** [comment]
@nakkeeran hey there. I am just getting a chance to look at this now. I see you closed it a bit after opening. Is this still an issue or did you resolve it on your own?

**Comment by nakkeeran** [comment]
No worries @scniro. i was missing `addon` css. 👍

**Comment by slobaton** [comment]
@nakkeeran which file did you missing? can you put your code please?? another thing too, I used the **npm install --save file system jsonlint** to have jsonlint
