### ISSUE TITLE
Codemirror addons not clear how to interact with them

### ISSUE THREAD

**Issue by mathiasbc** [scniro/react-codemirror2#101]
I can't find a way to consistently interact with Codemirror addons. I was trying to write a custom Find & Replace Component and I can't find a way to call the functions included in an addond like `search.js` for example. I give some more detail in my StackOverflow question. https://stackoverflow.com/questions/51274442/codemirror-react-implement-find-and-replace

**Comment by mjessome** [comment]
From you SO question, it seems that you're successfully able to call `getSearchCursor()` which returns to you a `cursor` object (according to the docs [you linked](https://codemirror.net/doc/manual.html#addons)). As documented, that cursor object has some methods on it through which you interact with the search cursor.

```js
// example replaceAll functionality
let cursor = this.codeMirror.getSearchCursor(this.state.find, false);
while (cursor.findNext()) {
  cursor.replace(replacement_text);
}
```

I'm not sure if the addon highlights on its own, you may need to use `cursor.from()` and `cursor.to()` in conjunction with `doc.setSelection()`
