### ISSUE TITLE
Unexpected Â character

### ISSUE THREAD

**Issue by nathan-wells** [scniro/react-codemirror2#104]
When codemirror field is empty, it appears as if it contains the "Â" character. Then when entering text, the same character appears after the pipe as part of the cursor.

**Comment by Locatus** [comment]
Hi! I am also experiencing this issue. I am unsure if it's a codemirror or react-codemirror2 issue. 
I also see this issue when there is an empty new line. 
![screen shot 2018-07-20 at 10 57 11 am](https://user-images.githubusercontent.com/6382962/43017030-bb55b67c-8c22-11e8-9691-03a5e2b4f760.png)

If anyone has an workarounds or solutions. I would love to hear it!

**Comment by scniro** [comment]
@nathan-wells @Locatus Hey! Thanks for opening this. Unfortunately this is the first I've heard or seen this. Unable to reproduce on my end. Can you share some specs with me? (OS, browser, versions, etc)

**Comment by Locatus** [comment]
Hi @scniro - Thanks for the quick response.

Quick info:
package.json: codemirror = 5.39.0. react-codemirror2=5.1.0
OS: Seen on Linux, macOS, and windows
Browser: Seen on firefox (linux), chrome (windows, macOS), and safari (macOS)

Interesting fact:
Do not see the issue when running my app through npm start (webpack), but see it when the app is built for tomcat.

I hope that was helpful. Let me know if you require any more info.

**Comment by scniro** [comment]
@Locatus interesting so I suspect the issue might have something to do with how webpack is bundling. Excuse me for being terribly oblivious here but I'm not at all familiar with what's all involved to build for tomcat. Is there a special process or version of node that webpack has to run on?

**Comment by Locatus** [comment]
I'm curious to know if the same scenario is happening for @nathan-wells. I'm going to start digging through what's different between the two. As well check into the doctype.

**Comment by scniro** [comment]
@Locatus cool let me know what you find. I stumbled across this and wonder if this could trigger any ideas? https://github.com/angular/angular-cli/issues/2077 Looks like they are seeing some issues with files not encoding correctly

**Comment by nathan-wells** [comment]
Package version: 4.3.0
OS: Windows 7
Browsers: Chrome & IE

I'm also using webpack and don't see the issue when running my app locally.

As far as doctype, I'm using <!doctype html>.

**Comment by scniro** [comment]
@Locatus @nathan-wells behold...

https://github.com/codemirror/CodeMirror/issues/5288

**Comment by nathan-wells** [comment]
The fix on my end was to update index.html to specify a utf-8 charset:
`<!DOCTYPE html>
<html>
  <link rel="stylesheet" href="./bundle.css" type="text/css" />
  <head>
  </head>
  <body>
    <div id="root"></div>
    <script src="./bundle.js" charset="utf-8"></script>
  </body>
</html>`
