### ISSUE TITLE
State issue brought over from codemirror1

### ISSUE THREAD

**Issue by jblevins1991** [scniro/react-codemirror2#109]
I have the following code below. Me and my senior developer have both confirmed that this.props.value always has a value inside of it being passed from the parent component, which it gets from redux. The issue I have is that during the parents render() function the value inside of codemirror1 and 2 never update to represent the value passed from the parent. I know this is a fork of codemirror so this might be fixed. I also am not sure if anybody else besides GraphiQL is using more than a single CodeMirror on the same screen. Any help is appreciated.

`render()` {

        return (
            <div className={this.props.className}>
                <div className="component-header">
                    <b>{this.props.name}</b>
                </div>

                <CodeMirror
                    className="codemirror"
                    value={this.props.value}
                    onBeforeChange={(editor, data, value) => {
                        this.setState({value});
                    }}
                    onChange={this.props.onChange}
                    options={this.props.options} /> 
            </div>);
    }`

**Comment by jblevins1991** [comment]
I figured it out. Sorry to waste anybody's time, but I was doing it wrong lol.

**Comment by scniro** [comment]
@jblevins1991 no worries glad you got it solved 👍
