### ISSUE TITLE
scroll attribute not working

### ISSUE THREAD

**Issue by pcolliander** [scniro/react-codemirror2#112]
I'm trying to set a coordinate with the `scroll` attribute, to essentially set the scrollTop to 0 (which I assume should work by setting `scroll={{ y: 0 }}`. But nothing is happening. 

I can manually set the scrollTop by 
`document.getElementsByClassName('CodeMirror-scroll')[0].scrollTop = 0` 

but then the scrollbar still stays in the same position, so would rather do it with the scroll attribute which I assume would update the state of the scrollbar as well.

Could it be a bug? I don't know how to investigate further. Using version `5.1.0`

**Comment by scniro** [comment]
@pcolliander do you have `autoScroll: true`? Maybe it's wanting an `x` value, whether or not it'd make a difference. Please share your implementation

**Comment by pcolliander** [comment]
I don't have `autoScroll: true`. I got around this issue by using [codemirror's scrollTo](https://codemirror.net/doc/manual.html#scrollTo) directly instead, so feel free to close.

**Comment by scniro** [comment]
@pcolliander closing per suggestion
