### ISSUE TITLE
The cursor jump to end of content when edit

### ISSUE THREAD

**Issue by falltodis** [scniro/react-codemirror2#114]
Excuse me 
I meet a problem that the  cursor would jump to end of content when editing. The main code should like 
```
  onChange = (editor, data, value) => {
    console.log({ data, value });
    this.setState({
      value,
    });
  };

  renderCodeMirror = () => {
    const options = {
      mode: 'javascript',
      lineNumbers: true,
      tabSize: '2',
    };

    return (
      <CodeMirror
        value={this.state.value}
        options={options}
        onChange={this.onChange}
      />
    );
  };
```
It is not work when setting autoCursor = false too.

**Comment by scniro** [comment]
@falltodis @rolandgnm try to use `onBeforeChange` as opposed to `onChange` per the [controlled usage](https://github.com/scniro/react-codemirror2#controlled-usage). Let me know if this helps?

**Comment by scniro** [comment]
@falltodis 👍

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
