### ISSUE TITLE
anyword hinting

### ISSUE THREAD

**Issue by shubhamsony** [scniro/react-codemirror2#116]
show-hint and anyword hinting doesn't registering event with codemirror instance
on log gives error console.log(CodeMirror.hint.anyword) 
Error:
TypeError: Cannot read property 'anyword' of undefined

**Comment by scniro** [comment]
Code? I have no idea what to make of this as-is. I suspect this isn't an issue with this lib but an implementation error you are encountering. Is [Any Word Completion Demo](https://codemirror.net/demo/anywordhint.html) example what you are trying to accomplish?

I suspect asking on [stackoverflow](https://stackoverflow.com/) will yield better results for you

**Comment by shubhamsony** [comment]
editor.on('keyup',function(cm,event){
            if(!cm.state.completionActive && (event.keyCode||event.which) != 13 && (event.keyCode||event.which)>64 && (event.keyCode||event.which)<91 && !event.altKey && !event.ctrlKey &&!ExcludedIntelliSenseTriggerKeys[(event.keyCode || event.which).toString()] ){
                cm.showHint({hint:CodeMirror.hint.anyword, completeSingle: false, alignWithWord:false});
                
            }
        })

giving error cannot read property anyword of undefined
i have already imported anyword-hint.js file

i think hint is not getting register with codemirror

**Comment by scniro** [comment]
@shubhamsony why are you not using the [`onKeyUp` component event](https://github.com/scniro/react-codemirror2#events-cont-wrapped-codemirror-events)? It's almost as if you're wanting to use the raw library instead. I'm going to close this out as this is clearly trending towards debugging your use-case and not an underlying issue with this component lib.
