### ISSUE TITLE
Uncontrolled: onChange fires when initial value is set

### ISSUE THREAD

**Issue by mb21** [scniro/react-codemirror2#119]
I'm using the uncontrolled component and loading the initial contents asynchronously. When it's arrived I make a call to `setState` which triggers a rerender with the new initial `value` prop. Unfortunately, that triggers the onChange function. So is there a reliable way to discriminate between an change coming from a changed `value` prop, or from the editor itself?

Using `onChange = function (editor, diffData, value) { ...`, I get the following for `diffData`:

```
{ from: {line: 0, ch: 0},
  origin: undefined
  ...
}
```

Is it a good way to just check whether `origin` is `undefined`? Or are there other cases when that's the case?

This may be related: https://github.com/JedWatson/react-codemirror/issues/5#issuecomment-162303642

Thanks for a great tool!

**Comment by scniro** [comment]
@mb21 thanks for opening this up. I haven't yet ran into this issue where the initial value in `onChange` is causing a problem. Trying to think of a workaround, would you be able to set a boolean through the `editorDidMount` prop? Perhaps set something such as `init = false` => `editorDidMount () => init = true`, and check of a `if init [...]` inside `onChange` This way you can ignore any erroneous  event firings until you set `init = true`, whether through the lifecycle mount or on the success of your ajax call.

**Comment by mb21** [comment]
Thanks for getting back to this. But I've since switched to the `Controlled` component, so this isn't an issue for me anymore... feel free to close this.

**Comment by scniro** [comment]
@mb21 will do, sorry for the terribly late reply, I'm glad you've been able to make forward progress 👍
