### ISSUE TITLE
Probably should have been a major version

### ISSUE THREAD

**Issue by danqing** [scniro/react-codemirror2#12]
Thanks for this library!

I feel like the 1.1.x release should probably be a major version. It moved `codemirror` to peer dependency, and the `require`s are also different.

Would be great if such breaking changes can result in a major version in the future.

Thanks!

**Comment by scniro** [comment]
@danqing you're right, I'm going to fix it - hold tight

**Comment by scniro** [comment]
[2.0.0](https://github.com/scniro/react-codemirror2/releases/tag/2.0.0) is up, and I pushed a fixed to [1.1.2](https://github.com/scniro/react-codemirror2/releases/tag/1.1.2) so hopefully others don't get stung on this. Thanks for bringing this up

**Comment by danqing** [comment]
Thanks!

**Comment by ticky** [comment]
> I removed all of the subsequent 1.x releases post 1.0.0 and have deprecated 1.x so this should not longer be an issue

Hey you should probably not do that because now anyone depending on any of those has code that doesn’t build for no discernible reason

**Comment by scniro** [comment]
@ticky Yea there wasn't really a best option at the time and I wanted to address it quick. 1.0.0 still exists. With the deprecation message I'd like to think it's good enough. Right now I don't really see any major consequences, perhaps a 404 if you had an exact version in your package.json e.g. `"react-codemirror2: 1.1.0"`

Did you have an error or are you speculating?

**Comment by ticky** [comment]
Version 1.1.1 was in my lockfile so [it broke CI](https://travis-ci.org/ticky/markdown-component-loader/builds/279633298).

**Comment by scniro** [comment]
@ticky my bad, shouldn't be a problem moving forward
