### ISSUE TITLE
Question: How to add custom hint method / helper for autocompletion?

### ISSUE THREAD

**Issue by raunaqss** [scniro/react-codemirror2#120]
Hey, I'm sorry if this is the wrong place to ask this question, just thought I may be able to get some help here.

So I'm trying to use a custom method for autocompletion and think there are 2 ways to do so with codemirror. 

1. Overwrite hint function as shown in this stackoverflow answer by codemirror author: https://stackoverflow.com/questions/19244449/codemirror-autocomplete-custom-list

2. Register a custom helper using the api `cm.registerHelper`

However, while trying the above solutions I discovered that only editor prop exposed by this component is `doc` and hence exposes only the `doc` api, leaving no way to register a helper or overwrite the javascript hint function.

I would really appreciate it if someone could point me in the correct direction in trying to solve the above. Thanks!

P.S. - Thanks for a great component, really helps use Codemirror with React / Webpack.

**Comment by raunaqss** [comment]
I got this working by doing the following, not sure if it's the best way, hence suggestions are welcome!

`import React, { Component } from 'react';
import {Controlled as CodeMirror2} from 'react-codemirror2';
var cm = require('codemirror');
import 'codemirror/addon/hint/show-hint';
import 'codemirror/addon/hint/javascript-hint';
import 'codemirror/mode/javascript/javascript';

var orig = cm.hint.javascript;
cm.hint.javascript = function (cm) {
	var inner = orig(cm) || { from: cm.getCursor(), to: cm.getCursor(), list: [] };
	inner.list.push("bozo");
	return inner;
};

class App extends Component {
	constructor(props) {
		super(props);
		this.state = {
			editorVal: "console.log('Hello, World');"
		};
	}
	render() {
		var { editorVal } = this.state;
		return (
			<CodeMirror2
				value={editorVal}
				options={{
					mode: 'javascript',
					theme: 'monokai',
					lineNumbers: true,
					extraKeys: { "Ctrl-Space": 'autocomplete' },
					autofocus: true,
					tabSize: 2
				}}
				onBeforeChange={(editor, data, value) => {
					this.setState({ editorVal: value });
				}}
				onChange={(editor, data, value) => {
					console.log(value);
				}}
				editorDidMount={(editor) => {
					console.log(editor);
				}}
			/>
		);
	}
}

export default App;`

**Comment by xiashei** [comment]
test

**Comment by xiashei** [comment]
> I got this working by doing the following, not sure if it's the best way, hence suggestions are welcome!
> 
> ```
> import React, { Component } from 'react';
> import {Controlled as CodeMirror2} from 'react-codemirror2';
> var cm = require('codemirror');
> import 'codemirror/addon/hint/show-hint';
> import 'codemirror/addon/hint/javascript-hint';
> import 'codemirror/mode/javascript/javascript';
> 

> cm.hint.javascript = function (cm) {
> 	var inner = orig(cm) || { from: cm.getCursor(), to: cm.getCursor(), list: [] };
> 	inner.list.push("bozo");
> 	return inner;
> };
> 
> class App extends Component {
> 	constructor(props) {
> 		super(props);
> 		this.state = {
> 			editorVal: "console.log('Hello, World');"
> 		};
> 	}
> 	render() {
> 		var { editorVal } = this.state;
> 		return (
> 			<CodeMirror2
> 				value={editorVal}
> 				options={{
> 					mode: 'javascript',
> 					theme: 'monokai',
> 					lineNumbers: true,
> 					extraKeys: { "Ctrl-Space": 'autocomplete' },
> 					autofocus: true,
> 					tabSize: 2
> 				}}
> 				onBeforeChange={(editor, data, value) => {
> 					this.setState({ editorVal: value });
> 				}}
> 				onChange={(editor, data, value) => {
> 					console.log(value);
> 				}}
> 				editorDidMount={(editor) => {
> 					console.log(editor);
> 				}}
> 			/>
> 		);
> 	}
> }
> 
> export default App;
> ```
It doesn't work as expected. You will get ‘bozo’ even if you input 'sdfsfw'. And this works for me: 
```
// eslint-disable-next-line eslint-comments/disable-enable-pair
/* eslint-disable import/extensions */
import React, { Component } from 'react';
import { UnControlled as CodeMirror } from 'react-codemirror2'
// import CodeMirror from 'react-codemirror'
import 'codemirror/lib/codemirror.css';
import 'codemirror/mode/sql/sql';
import 'codemirror/addon/hint/show-hint.css';
import 'codemirror/addon/hint/show-hint.js';
import 'codemirror/addon/hint/sql-hint.js';
// import 'codemirror/addon/hint/anyword-hint.js';
import 'codemirror/theme/blackboard.css';


export default class CodeEditor extends Component {
  constructor(props) {
    super(props)
    this.state = {
      value: '',
    }
  }

  render() {
    const options = {
      lineNumbers: true, // 显示行号
      mode: { name: 'text/x-sql' }, // 定义mode
      extraKeys: { Ctrl: 'autocomplete' }, // 自动提示配置
      theme: 'blackboard', // 选中的theme
    };
    return (
      <PageHeaderWrapper>
        <CodeMirror
          value={ this.state.value }
          onChange={(editor, data, value) => {
            console.log(data, value)
            const reg = /[a-z0-9]/i
            const { origin, text } = data
            console.log(text, text[0] === '.')
            if (origin === '+input' && (reg.test(text) || text[0] === '.')) {
                  editor.showHint({
                    tables: {
                      table1: ['column1', 'column2', 'column3', 'etc'],
                      another_table: ['columnA', 'columnB']
                    }, 
                    disableKeywords: true,
                    completeSingle: false,
                    // completeOnSingleClick: false,
                  })
                }
            this.setState({ value })
          }}
          options={ options }
         
        />
      </PageHeaderWrapper>
    )
  }
}

```

**Comment by NeroSolomon** [comment]
@raunaqss @xiashei Hi, could you help me  solve this problem?

In codemirror doc, I find that codemirror can use custom completion sources: https://codemirror.net/6/examples/autocompletion/

![image](https://user-images.githubusercontent.com/28894970/151133493-2a0185f1-9440-414f-bc41-3b28caded0db.png)


But I don't know how to config in react-codemirror2

Looking forward to your reply, thx

**Comment by BraveHead** [comment]
demo page: https://codemirror.net/examples/autocompletion/

 demo js : [ https://codemirror.net/examples/autocompletion/autocompletion.js](url)

read js and analyze ！

**Comment by BraveHead** [comment]
> demo page: https://codemirror.net/examples/autocompletion/
> 
> demo js : [ https://codemirror.net/examples/autocompletion/autocompletion.js](url)
> 
> read js and analyze ！

@NeroSolomon
