### ISSUE TITLE
Does not work in a simple setup

### ISSUE THREAD

**Issue by gajus** [scniro/react-codemirror2#128]
```js
// @flow

import React from 'react';
import ReactDOM from 'react-dom';
import {UnControlled as CodeMirror} from 'react-codemirror2'
import 'codemirror/lib/codemirror.css';
import 'codemirror/theme/material.css';
import 'codemirror/mode/xml/xml';
import 'codemirror/mode/javascript/javascript';

ReactDOM.render(<div style={{width: 500}}>
  <CodeMirror
  value='<h1>I ♥ react-codemirror2</h1>'
  options={{
    mode: 'xml',
    theme: 'material',
    lineNumbers: true
  }}
  onChange={(editor, data, value) => {
  }}
/>
</div>, document.getElementById('root'));

```

<img width="1920" alt="Screenshot 2019-03-10 at 15 56 29" src="https://user-images.githubusercontent.com/973543/54087674-2a232580-434d-11e9-83c6-dd0c7508b0ac.png">

It seems to be some window width detection issue.

The actual editor is loaded, but it is squeezed to a corner.

Can replicate with any browser.

**Comment by gajus** [comment]
* Can be replicated using `react-create-app@2`
* It is not a theme issue (tried different themes)
* It is not codemirror version (tried different codemirror versions)

**Comment by gajus** [comment]
Seems to be related to https://github.com/scniro/react-codemirror2/issues/106

This is definitely not a styling issue, though.

As mentioned in the original issue, seems to be a glitch in parent container width detection logic.

@erfansamieyan Did you find a solution?

**Comment by gajus** [comment]
This fixed the issue:

```diff
<CodeMirror
  value='<h1>I ♥ react-codemirror2</h1>'
  options={{
    mode: 'xml',
    theme: 'monokai',
    lineNumbers: true
  }}
  onChange={(editor, data, value) => {
  }}
+  editorDidMount={(editor) => {
+    setTimeout(() => {
+      editor.refresh();
+    }, 500);
+  }}
/>

```

<img width="1920" alt="Screenshot 2019-03-10 at 16 15 30" src="https://user-images.githubusercontent.com/973543/54087891-bdf5f100-434f-11e9-8fa2-e19a638e56dc.png">

This shouldn't be needed, though.

**Comment by erfansamieyan** [comment]
@gajus I think your problem is solved, however my issue was exactly the problem of not loading the css files. It seemed that the .css files were loaded fine in development mode, but it couldn't find them when the project was deployed. However I changed the way I included those needed css files into may `app.css` and the problem got solved.

**Comment by scniro** [comment]
@gajus was @erfansamieyan's suggestion able to help you get in the right direction? That refresh definitely shouldn't be necessary. Let me know!

**Comment by gajus** [comment]
> @gajus was @erfansamieyan's suggestion able to help you get in the right direction? That refresh definitely shouldn't be necessary. Let me know!

It is definitely not a CSS issue.

I tried inlining CSS and whatnot.

As you can see in the screenshots, the CSS is applied correctly.

If problem was CSS, then the refresh wouldn't help either.

**Comment by gajus** [comment]
Reproduced issue:

https://codesandbox.io/s/km69p35vy5

**Comment by gajus** [comment]
https://codesandbox.io/s/km69p35vy5

Unable to reproduce the issue.

Closing this until/if I reproduce the issue.

**Comment by scniro** [comment]
@gajus yes please reopen should you be able to reproduce this. My first suspicion is that something is being lazily handled by create-react-app. I've never used the tool so I'm admittedly unfamiliar with their opinions, but perhaps their chunking strategy is causing some sort of script race condition. I could be totally wrong also.
