### ISSUE TITLE
Not rendering code

### ISSUE THREAD

**Issue by jordyvandomselaar** [scniro/react-codemirror2#13]
When using those component with the following code:
```
import CodeMirror from "react-codemirror2"
import "codemirror/lib/codemirror"
import "codemirror/lib/codemirror.css"
import "codemirror/mode/php/php"
import "codemirror/theme/material.css"

const Editor = () => (
    <CodeMirror
        value='<h1>I ♥ react-codemirror2</h1>'
        options={options}
        onChange={(editor, metadata, value) => {
        }}
    />
)
```

All I get is a grey screen that I can't do anything with.
![image](https://user-images.githubusercontent.com/12712484/30785486-9cbb0592-a167-11e7-8112-0d0122b0affb.png)

There's no code inside, and clicking it doesn't do anything either.

![image](https://user-images.githubusercontent.com/12712484/30785499-cdbdcd3c-a167-11e7-9697-33c92ebc6f22.png)

But I still cannot edit code, nor does it render the `value` it was given.

**Comment by scniro** [comment]
Any errors? What is `options`? Looks undefined to me. Are you importing your resources correctly? Lot's to diagnose here...

**Comment by jordyvandomselaar** [comment]
Ah, yeah, forgot to add that;

```
const options = {
    mode: 'php',
    theme: 'material',
    lineNumbers: true
}
```

**Comment by scniro** [comment]
@jordyvandomselaar hmm I checked on my end with this basic setup, and all works. Could you spin up a quick repo that reproduces this? I'll be happy to help you out I just am not seeing an issue on my side at the moment

**Comment by scniro** [comment]
@jordyvandomselaar closing for now - please re-open if you are able to provide any more details
