### ISSUE TITLE
Cursor jumps to end when click to edit position

### ISSUE THREAD

**Issue by ultrox** [scniro/react-codemirror2#130]
Hello Again,

I'm using UnControled  component, and if click in the middle of text and trying to type, cursor jumps to end and append text.

![](https://j.gifs.com/nxxx6W.gif)

Possibly related with #2 

I have a [sandbox](https://codesandbox.io/s/k95lvmnln3)

**Comment by scniro** [comment]
@ultrox Thanks for opening this up and your interest in this component. Taking a look at your sandbox, with your state management, I'm led to believe you are wanting to use the [Controlled component](https://github.com/scniro/react-codemirror2#controlled-usage). You can manipulate the value through `onBeforeChange`. I know this method naming seems a bit strange, but it's a balancing act to play nicely with codemirror itself.

Here's an update sandbox that used both: https://codesandbox.io/s/wqm2wz0w7k. I'm going to close this out as I feel this will get you back up to speed :)
