### ISSUE TITLE
Scroll in Internet Explorer 11

### ISSUE THREAD

**Issue by felipepastor** [scniro/react-codemirror2#131]
Is anyone facing an issue related to the scroll in IE11? I tried all the options, but it doesn't seem enabled in IE11.

**Comment by scniro** [comment]
@felipepastor I have no way to reproduce this, not on a windows machine - sorry! Would gladly accept a PR if you can reproduce and pinpoint the issue

**Comment by scniro** [comment]
@felipepastor I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by elsigh** [comment]
closing as this is most likely a bug in CodeMirror itself instead of this wrapping lib
