### ISSUE TITLE
mode and theme don't work when used with electron-webpack

### ISSUE THREAD

**Issue by keenguy** [scniro/react-codemirror2#148]
First, I use `react-codemirror2` with electron and hand-written webpack configurations and it works good. 
However, when I try to rewrite using `electron-webpack`, the mode doesn't work. Specifically, `CodeMirror.modes` contains "markdown", which means that I've registered the "markdown" mode correctly. However, `instance.getMode()` return a null object as follows.
![Screen Shot 2019-07-21 at 16 49 44](https://user-images.githubusercontent.com/20125581/61589072-cd2b5c00-abd7-11e9-9827-bbfbaf0f4728.png)

I've tried a few things:
* apply a new theme, not working
* hand write a simple CodeMirror component, which works good
* copy the source code of `react-codemirror/index.js` into a new file under my project as a source file, and replace the line (line 68) `cm = require('codemirror');` with`cm = require('codemirror/lib/codemirror.js');`, then it works good

I guess it's mainly a problem of webpack configuration, while it's possible to solve in `react-codemirror2`. Webpack configuration is kind of complicated for me.

Any idea is welcome. Thanks.

**Comment by danielgolden** [comment]
I'm running into this exact issue, but I don't quite understand the last two solutions that you mentioned. Can you elaborate on these? I'd like to try one of them:
> - hand write a simple CodeMirror component, which works good
> - copy the source code of react-codemirror/index.js into a new file under my project as a source file, and replace the line (line 68) cm = require('codemirror'); withcm = require('codemirror/lib/codemirror.js');, then it works good
