### ISSUE TITLE
Controlled doesn't behave as expected

### ISSUE THREAD

**Issue by Hypnosphi** [scniro/react-codemirror2#149]
`Controlled` doesn't work if some transform is applied to the value from `onBeforeChange`, e.g.:

```
import "codemirror/lib/codemirror.css";
import React, { useState } from "react";
import ReactDOM from "react-dom";
import { Controlled as CodeMirror } from "react-codemirror2";

const App = () => {
  const [value, setValue] = useState("ooooo");

  return (
    <CodeMirror
      value={value.replace(/o/g, "p")}
      onBeforeChange={(editor, data, val) => {
        setValue(val);
      }}
    />
  );
};

ReactDOM.render(<App />, document.getElementById("root"));

```
https://codesandbox.io/embed/xenodochial-hooks-3srui

Expected: all the "o"s that you type get replaced with "p"s
Actual: the text you type is displayed as is

**Comment by scniro** [comment]
@Hypnosphi I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by elsigh** [comment]
I believe you want to mutate in your  setValue call - this doesn't look like a bug in this project

**Comment by Hypnosphi** [comment]
> mutate in your setValue call

You mean, apply the transform? No, it doesn't help. Why did you think it should?

https://codesandbox.io/s/throbbing-forest-9wr24?file=/src/index.js
```js
import "codemirror/lib/codemirror.css";
import React, { useState } from "react";
import ReactDOM from "react-dom";
import { Controlled as CodeMirror } from "react-codemirror2";

const App = () => {
  const [value, setValue] = useState("ppppp");

  return (
    <CodeMirror
      value={value}
      onBeforeChange={(editor, data, val) => {
        setValue(val.replace(/o/g, "p"));
      }}
    />
  );
};

ReactDOM.render(<App />, document.getElementById("root"));
```

**Comment by elsigh** [comment]
yep, you're right
