### ISSUE TITLE
Please can you provide support for React 16

### ISSUE THREAD

**Issue by danday74** [scniro/react-codemirror2#15]
I've just tried upgrading to React 16 and yarn warns me:

"react-codemirror2@2.0.0" has incorrect peer dependency "react@>=15.5 <16"

Please could you make this compatible with 16 so we can upgrade React to v16

Many thanks

PS When I upgraded I got errors with other modules before I hit any errors with this module so I cannot yet identify a specific problem but hopefully you know why this is not compatible with 16 and are able to fix it so that people using this module have an upgrade path in the future. Many thanks

**Comment by scniro** [comment]
Done! Thanks for opening this up so promptly. You should be able to pull down [2.0.1](https://github.com/scniro/react-codemirror2/releases/tag/2.0.1) via npm with the change. All seems to be working okay on my end locally as far as actually using react 16.x, but please let me know should you experience any further compatibility issues? Thanks again!

**Comment by danday74** [comment]
Many thanks - I will close this off - If I hit any issues I will raise another one - Your promptness is greatly appreciated :)
