### ISSUE TITLE
onChange alway use old props

### ISSUE THREAD

**Issue by nodece** [scniro/react-codemirror2#153]
Online code in https://codesandbox.io/s/casbin-9r1ul 
Preview in https://9r1ul.csb.app/

Log:
```
New Props 
▶Object {model: "basic"}
New Props 
▶Object {model: "basic_without_resources"}
Should use Latest Props 
▶Object {model: "basic"}
setModelCache basic 
New Props 
▶Object {model: "rbac"}
Should use Latest Props 
▶Object {model: "basic_without_resources"}
setModelCache 
```

`console.log` in `src/editor/model.tsx`

**Comment by schnerd** [comment]
Likely duplicate of #142

(FWIW I'm experiencing this too when using hooks)

**Comment by nodece** [comment]
@schnerd I use the `import { Controlled as CodeMirror } from 'react-codemirror2';`. It is working.
See: https://github.com/nodece/casbin-editor/blob/master/src/editor/editor.tsx
