### ISSUE TITLE
javascript mode does not work

### ISSUE THREAD

**Issue by oliverwatkins** [scniro/react-codemirror2#159]
If I have this : 

```
                    <CodeMirror
                        value={val}
                        options={{
                            mode: 'javascript'
                        }}
                        onChange={(editor, data, value) => {
                        }}
                    />
```
where val is :   

```
val = '//filter all out based on name\n' +
            '   input = input.filter(elem => elem.m.name === {{name}});\n' +
            '   //append country GDP\n' +
            '   input.forEach((elem) => {\n' +
            '        var result = await api.call({{API2}} + "" + input.countryCode)\n' +
            '        elem[GDP] = "" + result.countryGDP\n' +
            '   })' +
            '(num) => num + 1'
    }
```

then no formatting is displayed :  

![image](https://user-images.githubusercontent.com/9626175/66749549-a5b3fa80-ee79-11e9-9c20-211f02a96586.png)

**Comment by 1rosehip** [comment]
For me it works if I add javascript import before 'react-codemirror2' import like this:
```js
import 'codemirror/mode/javascript/javascript.js';
import {UnControlled as CodeMirror} from 'react-codemirror2';
```

Otherwise it doesn't work.

**Comment by oliverwatkins** [comment]
I tried exactly that code in the imports and my code looks like this :

```
                <CodeMirror mode="javascript"
                    onChange={(value) => {
                    this.props.handleScriptChange(value)
                }}
                    value={this.props.postProcessing}

                />
```
However what is shown does not look very good. It is formatting the "in" and "is" as purple from text like "include". "for" and "if" are ignored. It's almost as if it is trying to format in a different language.

![image](https://user-images.githubusercontent.com/9626175/67691982-60beb680-f997-11e9-8e96-5eb8037a092a.png)

**Comment by scniro** [comment]
@oliverwatkins @1rosehip I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by 1rosehip** [comment]
Hi @scniro, unfortunately I also have no time for open source these days. I also have my projects here on github almost abandoned.  I'm sorry :(

**Comment by elsigh** [comment]
I think the approach where you load the syntax for js as you mentioned is the correct solution
