### ISSUE TITLE
Using SQL hint addon

### ISSUE THREAD

**Issue by michaelmior** [scniro/react-codemirror2#160]
With react-codemirror, I could import `codemirror/addon/hint/sql-hint` and have `editor.hint.sql` defined on a CodeMirror instance. This doesn't work with react-codemirror2. Any idea why? (Seems to be related to #116)

**Comment by scniro** [comment]
@michaelmior I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by michaelmior** [comment]
@scniro Totally understand :) I've moved away from CodeMirror to [Prism](https://prismjs.com/) as I didn't need something so heavyweight so I wouldn't be the best person to help unfortunately.
