### ISSUE TITLE
Insert string at the current cursor position

### ISSUE THREAD

**Issue by AienTech** [scniro/react-codemirror2#166]
Hi there,

is there a way to insert a string at the current cursor position?

So I have a toolbar (a component) and there I have some buttons prepared for the user to add some pre-defined commands (like bold, underline, etc.) when clicking on each of them, a different type of strings should be inserted into the editor, where the cursor is set. how is this achievable with current configurations? is there any workaround?

many thanks

**Comment by scniro** [comment]
@AienTech I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by AienTech** [comment]
Hi @scniro , thanks for the message. I currently moved to another library, so, unfortunately, I can't help with the maintenance.

**Comment by jyxt** [comment]
You can insert at cursor position by using 
```
const doc = editor.getDoc()
const cursor = doc.getCursor()
doc.replaceRange('text', cursor)
```

You can get `editor` reference from `onChange` function arguments `(editor, data, value)`
