### ISSUE TITLE
6.0 missing in CHANGELOG

### ISSUE THREAD

**Issue by mhuggins** [scniro/react-codemirror2#168]
Hello!  I'm trying to see what changes come with 6.0, but it's not included in `CHANGELOG.md`.  Any chance of updating that for clarity?  Thanks!

**Comment by scniro** [comment]
@mhuggins I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by elsigh** [comment]
@mhuggins please feel free to send a PR
