### ISSUE TITLE
How to get editor instance?

### ISSUE THREAD

**Issue by andymok221** [scniro/react-codemirror2#17]
I am migrating from react-codemirror. I would like to know how to get code mirror instance or is it supported?

**Comment by scniro** [comment]
The instance is being passed as a parm on about every event e.g. `onChange(editor, metadata, value)` where `editor` is the insnace. At what point do you want the instance?

**Comment by andymok221** [comment]
I tried to use the instance in `editorDidMount` but I cannot do `registerHelper` on it.

**Comment by euZebe** [comment]
@andymok221 Which mistake did you maid, and how did you fix it ?
I am trying to call registerHelper, but it seems not to be available at the level I espect it to be:
```
<CodeMirror
  value={value}
  options={codeMirrorOptions}
  editorDidMount={(editor) => {
    editor.registerHelper(......); // => editor.registerHelper is not a function
  }}
/>
```

**Comment by scniro** [comment]
@andymok221 [CodeMirror.registerHelper](https://codemirror.net/doc/manual.html#registerHelper) is on the library, _not_ the instance. You'd need to do something like the following...

```jsx
const cm = require('codemirror');

// [...]
<CodeMirror
  editorDidMount={(editor) => {
    cm.registerHelper(/* [...] */); 
  }}
/>
```
