### ISSUE TITLE
Can't change `cursor.line` after Codemirror mounts

### ISSUE THREAD

**Issue by stoplion** [scniro/react-codemirror2#173]
https://codesandbox.io/s/heuristic-neumann-kvkjn

```
cursor={{
          line: activeLine,
          ch: 1
        }}
```

Is this intended? Once the component mounts, the line property seems like it can't be changed.

**Comment by scniro** [comment]
@stoplion I am a lot shorter on time these days as when I started this project. Codemirror & React APIs are moving to quickly for me to keep atop of for the day-to-day. I am looking for a co-maintainer of this project. Please contact me directly if you are interested. Thank you for understanding.

**Comment by sukrut-gs** [comment]
I will have a look at this.

**Comment by sukrut-gs** [comment]
@stoplion you can pass key to CodeMirror like this
`<CodeMirror
        key={activeLine}
        value={`
        one
        two
        three
        four
      `}
        options={{
          lineNumbers: true,
          styleActiveLine: true
        }}
        cursor={{
          line: parseInt(activeLine,10),
          ch: 1
        }}
      />`

**Comment by elsigh** [comment]
looks like a workaround
