### ISSUE TITLE
How do you change the the height of the editor?

### ISSUE THREAD

**Issue by swimminginlove** [scniro/react-codemirror2#179]
I've tried to change the height of the editor with all the options I could find but the editor won't change.

It just covers the top 30% of the screen and nothing more.

**Comment by scniro** [comment]
Likely need to look into your css/styling, this package don't concern itself with height specifics

**Comment by dzucconi** [comment]
Supporting the `style` prop and spreading rest props would be useful for those of us not using CSS, however.
