### ISSUE TITLE
How to prevent default  paste event

### ISSUE THREAD

**Issue by 9aoyang** [scniro/react-codemirror2#180]
In some situation, I need to disable the default paste event use custom, why [7.0.0](https://github.com/scniro/react-codemirror2/commit/1801460b2c35db1372afe221b070143b6e52199c#diff-38682f47b0cf12c516bc3714fc45d0fdL305) remove the event argument in onPaste event, Is there any other way to disable the default paste event

**Comment by scniro** [comment]
@9aoyang hmh, let me get back to you on that. I did indeed remove the event as the new typings lib suggested the events were no longer in the function signatures of `cut` `copy` & `paste`. Please use 6.0.1 until I am able to get you better information. Thanks!

**Comment by 9aoyang** [comment]
Thanks a lot！

**Comment by scniro** [comment]
@9aoyang yep this was indeed a problem! Keeping parity with library changes & typings are always tricky 😸 This is hopefully fixed with the [7.1.0 release](https://github.com/scniro/react-codemirror2/releases/tag/7.1.0). Can you please verify when you find a moment?

**Comment by scniro** [comment]
@9aoyang going to close this, please re-open should you experience the same issue. Thanks!

**Comment by 9aoyang** [comment]
I'm sorry for replying to you late. I just upgraded and now it works fine : )
