### ISSUE TITLE
The sample doesn't work for me

### ISSUE THREAD

**Issue by Dmunch04** [scniro/react-codemirror2#184]
The sample code in the README results in this for me:
![image](https://user-images.githubusercontent.com/30357821/81400214-e08ac200-912c-11ea-9eb6-c0a9df58da7a.png)
And when I press a button it just goes further down. Any ideas what could cause this?

**Comment by Dmunch04** [comment]
Sorry. I didn't know you had to do those imports which were shown further down. It fixed it and so I'll close now

**Comment by Ajamuar** [comment]
I am still struggling with the same problem.

I am trying to render a JSON, but there's no output at all.

[https://codesandbox.io/s/youthful-pine-5tnh9?file=/src/App.tsx](url)
