### ISSUE TITLE
在antd@4.x里面这样用就报错，怎么解决

### ISSUE THREAD

**Issue by bibiehy** [scniro/react-codemirror2#187]
antd@4.2.0
react-codemirror2@7.1.0
codemirror@5.53.2

import { UnControlled as CodeMirror } from 'react-codemirror2';
antd自身组件不报错，比如 Input

![image](https://user-images.githubusercontent.com/35096473/82440781-792b2580-9acf-11ea-8550-1a8b3bbb5404.png)

**Comment by elsigh** [comment]
do not understand the issue
