### ISSUE TITLE
Updating the value resets cursor position

### ISSUE THREAD

**Issue by rbuchmann** [scniro/react-codemirror2#2]
Hi, thanks for writing this, I used react-codemirror before but ran into https://github.com/JedWatson/react-codemirror/issues/121 ...
Now, when I update the state used in the value prop in onValueChange, the cursor resets to the beginning of the text. Any hint on how to prevent that?

**Comment by scniro** [comment]
Hey @rbuchmann! Thanks for opening this up. I pushed some new changes for this in hopes that it'll fix your issue. I added a `resetCursorOnSet` prop that defaults to `false` should a user want to reset the cursor as you are experiencing (unsure if this would be even really valuable).

Either way, the internal cursor position should now be preserved by default when modifying `value`. [0.0.8](https://www.npmjs.com/package/react-codemirror2) should be published to npm. Could you pull down and let me know if your issue is resolved?

**Comment by MartinHaeusler** [comment]
I'm writing a react-redux app, and it would be very useful to even have the text selection and cursor position (as well as the scroll bar position) of the editor available as prop / callback pairs. Do you think that would be possible?

**Comment by scniro** [comment]
@MartinHaeusler most likely I can do that. Would you mind explaining a bit more? I'm gathering that you'd like to pass text selection, cursor position, and scrollbar position as props. That should be easy enough. And then, are you suggesting a callback for each as they change. I'd envision something like this...

```jsx
<CodeMirror
  scrollPos={scrollPos}
  cursorPos={cursorPos}
  textSelection={textSelection}
  onScrollPosChange={(scrollPos)=> {
  }}
  onCursorPosChange={(cursorPos) => {
  }}
  onTextSelectionChange={(textSelection) => {
  }}/>
```
I'll have time tomorrow to see what I can work up - but please let me know if this is indeed what you're asking for. Thanks!

**Comment by MartinHaeusler** [comment]
Yes, that's exactly what I was getting at. In a react-redux app, you will want to have as much of all that information (cursor position, scroll bar position etc.) as possible in the redux store. It's especially important e.g. when the actual react component is unmounted and re-created later on to have the same state again (think about the content of tabs in a tab sheet). Only the store state is available which you pass into the component as props, and you want to re-create the old editor state as closely as possible to the original one.

**Comment by scniro** [comment]
@MartinHaeusler okay I gave this a shot and the latest changes should be releases in [0.0.9](https://github.com/scniro/react-codemirror2/releases/tag/0.0.9) via npm. Check out the [prop wrapped codemirror programming api](https://github.com/scniro/react-codemirror2#prop-wrapped-codemirror-programming-api) portion of the doc. All the callbacks should be optional but also provide the prop/callback pair you were wishing to have. When you get some time can you try this out and share some feedback? Thanks!

**Comment by rbuchmann** [comment]
Hi @scniro thanks for the quick fix and sorry for being late with my reply. Unfortunately I can't test if it works, because now when I change something in the editor, I get a "string.split is not a function" error deep in codemirror.js. I am running the app from electron if that helps.

**Comment by rbuchmann** [comment]
Nvm, I think it was just due to me using the same handler signature as in react-codemirror(1). I'll experiment more and get back to you.

**Comment by rbuchmann** [comment]
It works, thanks a lot!

**Comment by joshy-joy** [comment]
Hi,
I have the same problem with codeMirror in Angular. Once I call the getSelection( ) method. My cursor is reset back to position 1. How could I solve this issue ?
