### ISSUE TITLE
typescript definition

### ISSUE THREAD

**Issue by agdolla** [scniro/react-codemirror2#20]
Hi
Do you plan to create a typescript definition ?
I'm using @types/react-codemirror but I needed to change it as your module exports different object

**Comment by scniro** [comment]
Hello,
I am working on this now and plan to be done soon (day or so). I'll update here once it's available.

Actually, before I publish up a new version would you be willing to test out the changes privately to make sure all looks good as I am not an avid typescript user (it's possible I'll miss something here or there).

**Comment by agdolla** [comment]
@scniro if you send it I can test it, too

**Comment by scniro** [comment]
@agdolla Hey there. So I took a stab at this and spun up a new repo at [react-codemirror2-types](https://github.com/scniro/react-codemirror2-types). This contains the packed up `.tgz` package. You can download it and install manually as if it were available on npm, but you'll instead include the file in your source and `npm install react-codemirror2-3.0.0-alpha.tgz`

I'm not going to publish up to the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repo, but instead ship this modules with typings included. I'll plan to bump a new major version if this looks good to us after some use. A second set of eyes is super useful so I appreciate your willingness to test with me.

I stumbled across a few interfaces with missing/incorrect signatures in [@types/codemirror](https://www.npmjs.com/package/@types/codemirror) so I'll plan to get a PR sent their way to fix what I discovered. Regardless, those won't hold up your testing but only my source development.

Look forward to hearing back about your findings!

**Comment by agdolla** [comment]
@scniro  Hi I tried to used, but how do you specify a mode?
I mean in js you have this:
```javascript
<CodeMirror
  value='<h1>I ♥ react-codemirror2</h1>'
  options={{
    mode: 'xml',
    theme: 'material',
    lineNumbers: true
  }}
  onChange={(editor, metadata, value) => {
  }}
/>
```

in typescript there is no options defined

also
```javascript
export interface IDefineModeOptions {
    name: string;
    fn: () => any;
}
```

fn could be something like

``` javascript
fn: () => codemirror.Mode
```

**Comment by scniro** [comment]
I totally overlooked `options`. I was trying to get all the callbacks and most props typed. I'll work through `options` today. I also like the `fn: () => codemirror.Mode` suggestion. I'll try to get a new version pub'd up to the test repo later today

**Comment by scniro** [comment]
@agdolla I pushed up a new binary to the test repo, could you install and let me know if this revision looks better? In the meantime, I have begun to write some unit tests to ensure I didn't break anything. I am actually having a bit of difficulty doing this because of the nature of the library rendering the editor on a ref (something about portals). I'll keep going, but I'll likely just spend some time manually testing everything.

If this looks good, I'll publish up to the main repository so the types will come down with the new version. If you have any more suggestions please keep them coming 😎

**Comment by agdolla** [comment]
LGTM :+1:

**Comment by scniro** [comment]
@agdolla hey I wanted to let you know that I haven't forgotten about this. I came across a few annoyances while getting the types all worked out and I wanted to take the opportunity to tackled everything at once. You can check out #22 for a little about what I have going on. I am hoping to roll out the new changed in a 3.x release in the coming days.

**Comment by scniro** [comment]
@agdolla  This should now be fixed in [3.0.0](https://github.com/scniro/react-codemirror2/releases/tag/3.0.0). 

I changed the core API a bit, please check out whats [new in 3.0.0](https://github.com/scniro/react-codemirror2#new-in-300) to get up and running.

Please let me know if this is resolved! 😸

**Comment by agdolla** [comment]
@scniro  sorry I did not have time to test it :(

**Comment by scniro** [comment]
@agdolla It's all good, we all have a crammed schedule. There haven't been any drastic changes to the typings since you last tried it out. I opted to close this for now but please re-open should you encounter any difficulties. Thank you for the collaboration!

**Comment by PatrickKunz** [comment]
The type definitions do not work with the latest version. I get following errors:

`ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:6:26 
    TS2694: Namespace ''codemirror'' has no exported member 'Mode'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:14:24 
    TS2694: Namespace ''codemirror'' has no exported member 'Position'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:15:22 
    TS2694: Namespace ''codemirror'' has no exported member 'Position'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:22:42 
    TS2694: Namespace ''codemirror'' has no exported member 'Doc'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:23:33 
    TS2694: Namespace ''codemirror'' has no exported member 'Position'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:26:47 
    TS2694: Namespace ''codemirror'' has no exported member 'Editor'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:27:25 
    TS2694: Namespace ''codemirror'' has no exported member 'EditorConfiguration'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:36:25 
    TS2694: Namespace ''codemirror'' has no exported member 'Position'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:43:53 
    TS2694: Namespace ''codemirror'' has no exported member 'EditorChange'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:46:53 
    TS2694: Namespace ''codemirror'' has no exported member 'Position'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:62:53 
    TS2694: Namespace ''codemirror'' has no exported member 'ScrollInfo'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:67:26 
    TS2694: Namespace ''codemirror'' has no exported member 'EditorConfiguration'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:75:58 
    TS2694: Namespace ''codemirror'' has no exported member 'EditorChange'.
ERROR in [at-loader] ./node_modules/react-codemirror2/index.d.ts:82:59 
    TS2694: Namespace ''codemirror'' has no exported member 'EditorChange'.`

Is this a problem on my side or did the something break the difinitions?
