### ISSUE TITLE
How to use JSON Linting

### ISSUE THREAD

**Issue by StinglSa** [scniro/react-codemirror2#21]
Hi,

could you maybe point me to a solution how to use json linting in react-codemirror2?
When i use mode javascript i get error highlighting in code but no gutters. This works with the react-codemirror 1 version.  But as r_cm1 is outdated i would like to use this version.

is use the following option set 
options={{
                                mode: 'application/json',
                                theme: 'material',
                                lineNumbers: true,
                                lineWrapping: true,
                                lineHeight: 10,
                                lint: true,
                                gutters: ["CodeMirror-lint-markers"],
                            }}
thanks in advance
Greetings Sascha

**Comment by scniro** [comment]
This should work fine, I just tested it locally. I am suspecting you are not getting through the setup correctly. The old repo had a similar issue seen here https://github.com/JedWatson/react-codemirror/issues/89

I made sure to include all the necessary files, which, on my end consisted of...

```jsx
require('codemirror/addon/lint/lint');
require('codemirror/addon/lint/json-lint');
```

```scss
@import 'codemirror/addon/lint/lint.css';
```

I was then presented with an error in the browser...

> window.jsonlint not defined, CodeMirror JSON linting cannot run

So I added the following...

window.jsonlint = require('jsonlint');

I tested this with `JSHINT` as well for javascript mode and all seems to be working

**Comment by StinglSa** [comment]
I use the same imports as you mentioned. After import jsonlint the error is gone but still no linting. maybe I do something wrong with the jsonlint import. I guess I'll try again with minimal example. thx for help!

**Comment by scniro** [comment]
I had a lot of weirdness going on with requiring jsonlint with webpack, similar to what's going on here https://github.com/zaach/jsonlint/issues/57. You might need to explore a little bit to get around this. Let me know what you find!

**Comment by slobaton** [comment]
@scniro I tested with JSHINT and the linter works, but with jsonlint does not working
for that I installed jsonlint using **npm install --save file system jsonlint**
```import { Controlled as CodeMirror } from 'react-codemirror2';
import jsonlint from 'jsonlint';
import { JSHINT } from 'jshint';

import 'codemirror/lib/codemirror.css';
import 'codemirror/addon/lint/lint.css';
import 'codemirror/addon/lint/lint';
import 'codemirror/addon/lint/json-lint';
import 'codemirror/addon/lint/javascript-lint';
import 'codemirror/mode/javascript/javascript';

import 'codemirror/addon/edit/closebrackets';


window.JSHINT = JSHINT;
window.jsonlint = jsonlint;

const options = {
  mode: 'javascript',
  lineNumbers: true,
  lineWrapping: true,
  autoCloseBrackets: true,
  gutters: ['CodeMirror-lint-markers'],
  lint: true,
};```
Can you upload some sample code please?

**Comment by StinglSa** [comment]
the problem here is not the jsonlint in my opinion but that it wont show linting errors in codemirror.
I used it for linting before refresh the state.  Here how i import it:
`
import jsonlint from 'jsonlint/lib/jsonlint'
window.jsonlint = require("jsonlint");

//example usage
let json_data = {"key": 1, "key2": 2};
jsonlint.parse(json_data) //this will throw an error if linting fails
`

**Comment by aprilandjan** [comment]
@slobaton I tried with `jsonlint` and it won't work because the `jsonlint` package from `npm` does not work with `webpack` due to its module declaration codes. I had to fallback to `jshint`😭

**Comment by christopherblaser** [comment]
https://github.com/codemirror/CodeMirror/pull/5377 @aprilandjan 

Also if you want to require jsonlint, there's a fork of jsonlint that works (as jsonlint is unmaintained) -> jsonlint-mod

**Comment by justnewbee** [comment]
i went into this as well, and solution from @aprilandjan works.
just one advice, you don't have to put jsonlint into window object.

codemirror shall fix this too.

**Comment by Relequestual** [comment]
For anyone looking at this today, looks like codemirror still uses the non fixed version of `jsonlint`.
Using the `jsonlint-mod` npm package, I managed to get lint errors highlighted easily.

```javascript
const jsonlint = require("jsonlint-mod");
window.jsonlint = jsonlint;

const cmOption = {
  mode: 'application/json',
  gutters: ["CodeMirror-lint-markers"],
  styleActiveLine: true,
  lineNumbers: true,
  line: true,
  lint: true,
};
```

Nothing else required.

I dislike having to put `jsonlint` on window, but it works for now, and I know I'll need to create my own linter function in the future anyway, so I'll copy the above alternative solution at that point, but without using `window`.

**Comment by adamxy** [comment]
> ```js
> const jsonlint = require("jsonlint-mod");
> window.jsonlint = jsonlint;
> ```

options={{
                        mode: 'javascript', 
                        theme: 'material',
                        gutters: ['CodeMirror-lint-markers'],
                        lineNumbers: true,
                        lint: true,
                        line: true
                    }}
`
![image](https://user-images.githubusercontent.com/11717062/64597767-fc489780-d3e8-11e9-916f-e7c3dd125f71.png)
`

**Comment by hrvoj3e** [comment]
In vanilla JS this works

```text
https://cdnjs.cloudflare.com/ajax/libs/jsonlint/1.6.0/jsonlint.min.js
https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.4/addon/lint/json-lint.min.js
https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.59.4/mode/javascript/javascript.min.js
```

```js
var editor = CodeMirror.fromTextArea(document.getElementById("editor"), {
    lineNumbers: true,
    styleActiveLine: true,
    theme: "material",
    mode: "application/json",
    gutters: ["CodeMirror-lint-markers"],
    lint: true
});
```

**Comment by mrprofessor** [comment]
`json-lint` didn't work for me, however with `javascript-hint` and `javascript-lint`, it worked.

```js
import 'codemirror/addon/lint/lint.js'
import 'codemirror/addon/lint/lint.css'
import 'codemirror/addon/lint/javascript-lint.js'
import 'codemirror/addon/hint/javascript-hint.js'

window.JSHINT = JSHINT;

const options = {
        mode: 'application/json',
        lint: true,
        gutters: [ "CodeMirror-lint-markers"],
      }

```
