### ISSUE TITLE
Lagging page performance on Long Text...

### ISSUE THREAD

**Issue by eminx** [scniro/react-codemirror2#26]
Hi!

Thanks for creating this component.

When we receive a quite long text and insert in the component as value, the whole page becomes very slow (only the page)...

Do you know what could be the reason? And how we can fix it??

Thanks!

**Comment by scniro** [comment]
Hello,

Is this for the controlled or uncontrolled variant? Is the component slow to respond to input changes, or is your app overall slow by simply including this? Please share your implementation and I can take a look.

**Comment by scniro** [comment]
@eminx So when using `react-codemirror` originally, was the performance still slow? I immediately suspect `codemirror` itself may be attributed to your bottleneck. If so, I am unsure if I am unable to offer a solution as this component is a simple wrapper around that library.

I came across [CodeMirror/397](https://github.com/codemirror/CodeMirror/issues/397) - does this apply to your situation?

> Your XML file is a single line. CodeMirror doesn't handle extremely long lines very well. This is a known issue.

**Comment by eminx** [comment]
Hmm, you are probably right. Yes, the performance was much slower with `react-codemirror`.

This kind of seems relevant indeed. Not sure if I can still fix the problem, but I'll probably show part of the content anyways.

Length of the string that causes lagging is counted at *352901* Maybe it helps :)

Thanks to you!

**Comment by scniro** [comment]
@eminx wow that's a long line! Is there a way you can format that in a way that is mentioned in the issue I referenced? I believe that are some techniques to do so.

I am going to close this out for now as it seems to be directly `codemirror` related

**Comment by eminx** [comment]
Yes! I will look into it today and will update here, how/if I manage to do it. 

Thanks a lot!
