### ISSUE TITLE
Any help with this error "cm is not a function" in nextJs

### ISSUE THREAD

**Issue by Byiringiro-saad** [scniro/react-codemirror2#291]
Anyone met this error!
I am unable to use react-codemirror2 in nextJs, am always getting this error!
![image](https://user-images.githubusercontent.com/61246755/191056497-d56a3a3e-2896-4a35-99af-6477cf2336f9.png)
![image](https://user-images.githubusercontent.com/61246755/191063172-1a18fda4-8dc0-45df-aea0-de52ebf76a7b.png)

**Comment by Andrewkz** [comment]
i also have this problem.

**Comment by Andrewkz** [comment]
> Anyone met this error! I am unable to use react-codemirror2 in nextJs, am always getting this error! ![image](https://user-images.githubusercontent.com/61246755/191056497-d56a3a3e-2896-4a35-99af-6477cf2336f9.png) ![image](https://user-images.githubusercontent.com/61246755/191063172-1a18fda4-8dc0-45df-aea0-de52ebf76a7b.png)

you can try to install lower version of codemirror. like v5.56.0

**Comment by Byiringiro-saad** [comment]
It worked after downgrading codemirror to v5.56.0
Thanks alot @Andrewkz

**Comment by kaushal1999** [comment]
downgrading to codemirror v5.56.0 not working
@Andrewkz
