### ISSUE TITLE
Mobile browser error: Cannot read property 'setOption' of undefined

### ISSUE THREAD

**Issue by cephirothdy2j** [scniro/react-codemirror2#32]
We're getting an error thrown in Chrome for Android 7 and MS Edge Mobile:

```
TypeError: Cannot read property 'setOption' of undefined
```

Looks like it's being thrown [here](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L296).

Per [Codemirror's browser support page](http://codemirror.net/#browsersupport), mobile browser support is experimental. We can catch the mobile browsers in our application and render a textarea instead, but I thought maybe this error was introduced by recent changes made to your library since we never saw the issue prior to our release a couple days ago.

Thanks!

**Comment by scniro** [comment]
Hey again thanks for opening this up. [I previously blocked all rendering](https://github.com/scniro/react-codemirror2/commit/10678e654e9ff84bb9d90b16d4058c208a10646b#diff-168726dbe96b3ce427e7fedce31bb0bcL15) on mobile but was then suggested to support it [as seen in 28](https://github.com/scniro/react-codemirror2/issues/28). It should now render on mobile, but I am curious if the error is specific to only those two browsers (or possibly others) as I can see it on my iphone okay, also some basic emulating in my browser, and if so, would you have any clue as to why?

**Comment by cephirothdy2j** [comment]
Thanks. I'm able to replicate on my iPhone 7 with iOS 11 (the error appeared in our tracker as I viewed the page); I can also replicate in BrowserStack on a Galaxy S8 in Chrome. See attached; the first screenshot is from the desktop version where the codemirror component is mounting correctly; the next two are from my iPhone and from BrowserStack, respectively. The input simply fails to render and the error throws.

<img width="817" alt="screen shot 2017-11-05 at 5 40 16 pm" src="https://user-images.githubusercontent.com/881769/32420145-e4474b98-c253-11e7-9176-b1cc8195f0ac.png">

![img_7226](https://user-images.githubusercontent.com/881769/32420153-fe68b3cc-c253-11e7-95d6-efb9d1f90bc4.PNG)

<img width="740" alt="screen shot 2017-11-05 at 6 04 22 pm" src="https://user-images.githubusercontent.com/881769/32420157-060acbba-c254-11e7-8335-99532564618c.png">

**Comment by cephirothdy2j** [comment]
Sorry, this is on me; I just upgraded to 3.0.7 and the issue is resolved. Thanks for bearing with me!

**Comment by scniro** [comment]
No worries! I'm glad this was easy for you to get back up and running 😄
