### ISSUE TITLE
thank you for being better than the original 

### ISSUE THREAD

**Issue by no-stack-dub-sack** [scniro/react-codemirror2#33]
took me a while to realize there was a fork, I was actually about to do it myself when I found this. A RCM project that is actually maintained and modern! SO much better. Deserves more stars. Thanks! 

using it for a little pet project just for fun: http://cs-playground-react.surge.sh/

Feel free to close this, just had to say it.

**Comment by scniro** [comment]
@no-stack-dub-sack Thank you for the kind words! I'm glad to see this is being used more and hopefully the momentum keeps up. If you have any issues at all please open something up and I'll gladly help you out with it 😎 Thanks again 👍

**Comment by no-stack-dub-sack** [comment]
@scniro will do! but so far so good. I love the improvements over the original, such as the editor instance being passed down into the callbacks. Super convenient! Keep up the good work.
