### ISSUE TITLE
why the editor look like this

### ISSUE THREAD

**Issue by huangjiatian** [scniro/react-codemirror2#34]
![9d1a0c14-a9c0-459f-a26b-f209a6e94f3a](https://user-images.githubusercontent.com/33113111/32938856-8d46795e-cbb8-11e7-8461-738c646f5366.JPG)
hi,
i got the issue like this
the text runs outside the editor
and the editor will longer and longer when re-render every time

**Comment by jasonrhaddix** [comment]
Just in case someone comes across this....

You need to make sure you add the package dependencies, and import the correct mode and styles. Make sure you thoroughly read the README and initial setup documentation.
