### ISSUE TITLE
onChange not working

### ISSUE THREAD

**Issue by stoplion** [scniro/react-codemirror2#39]
onChange not working for Controlled

**Comment by scniro** [comment]
Closing for total absence of details

**Comment by stoplion** [comment]
[onChange not working for Controlled](https://codesandbox.io/s/pkjl502k4j)

**Comment by stoplion** [comment]
Change this to UnControlled and it will work

**Comment by scniro** [comment]
@stoplion  You're using the component incorrectly. Did you look at the docs? I thought the examples were pretty clear. [There's even a demo site!](https://scniro.github.io/react-codemirror2/)

```
import {Controlled as CodeMirror} from 'react-codemirror2'

<CodeMirror
  value={this.state.value}
  options={options}
  onBeforeChange={(editor, data, value) => {
    this.setState({value}); // state management here
  }}
  onChange={(editor, data, value) => {
    // downstream callback
  }}
/>
```

**Comment by stoplion** [comment]
ok makes sense thz
