### ISSUE TITLE
[Question] Is it possible to get current value of editor on external event without setting state?

### ISSUE THREAD

**Issue by vspedr** [scniro/react-codemirror2#41]
Hello,

I'm using an UnControlled codemirror component in a form in my React+Redux application. It seems a bit of an overkill to me to have to call setState in my component on every change, so I'm wondering if there is a `getValue()` or similar method in the editor instance that I can use, for example, on a form submit event? Just like how I can get an input's value using refs like in [this example from React docs](https://reactjs.org/docs/uncontrolled-components.html)

**Comment by scniro** [comment]
@vspedr you can get the editor through many [events](https://github.com/scniro/react-codemirror2#events). Check out `editorDidMount` your case, the following should work...

```jsx
constructor() {
  this.instance = null; // store here on `editorDidMount`
}

handleSubmit() {
  if(this.instance)
    let value = this.instance.getValue();
}

render() {
  <form onSubmit={this.handleSubmit.bind(this)}>
    <CodeMirror editorDidMount={(editor) => { this.instance = editor }}/>
    <button>submit</button>
  </form>
}
```

**Comment by vspedr** [comment]
Thanks @scniro for the clarification! This worked nicely!
