### ISSUE TITLE
Codemirror do not show the init value for the first time

### ISSUE THREAD

**Issue by christtrc** [scniro/react-codemirror2#42]
I encounter a strange problem. I use Codemirror 2 **Controlled** component. When the first time to load and show the codemirror 2 in my app, the initialized value was not show. and then if I reenter the page, the value will be show correctly. Even if I hard the value in the `render` method.

```
render() {
...
const initContent = '12345';

return (
 ...
<CodeMirror
                value={initContent}
                options={options}
                onBeforeChange={(editor, data, value) => {
                  this.setState({ markdownText: value });
                }}
                onChange={(editor, value) => {
                  // console.log('controlled', { value });
                }}
              />
...
);
}
```

**Comment by scniro** [comment]
Hm, I'm not totally sure what's going on here. It appears you are using the controlled variant but your `initContent` is not on your local state. In the `onBeforeChange`, I see you are setting `markdownText`. Why not initialize this with a default value as such...

```jsx
constructor() {
  this.state = {
    markdownText: '12345'
  }
}

render() {
  <CodeMirror
    value={this.state.markdownText}
    onBeforeChange={(editor, data, value) => {
      this.setState({ markdownText: value });
    }}
  />
}
```

Wouldn't this essentially achieve the same thing?

**Comment by neewbee** [comment]
I've got the same issue
