### ISSUE TITLE
How to add autocompletion?

### ISSUE THREAD

**Issue by TheMegaTB** [scniro/react-codemirror2#43]
Is there any way to access the CodeMirror object as it was possible in `react-codemirror` through `editorRef.getCodeMirrorInstance()`?
If that ain't possible is there any other way to add completion/show-hint without access to it?

Calling `showHint` on the editor object (accessed through the keybinding callback) seems to have no effect.

**Comment by scniro** [comment]
Getting the instance is now up to storing it through the callbacks (most every one returns it). Maybe check out `editorDidMount` for this....

```jsx
constructor() {
  this.instance = null; // store here on `editorDidMount`
}

handleSubmit() {
  if(this.instance)
    let value = this.instance.getValue();
}

render() {
  <CodeMirror editorDidMount={(editor) => { this.instance = editor }}/>
}
```

Now with `this.instance`, you can do whatever you wish that the raw codemirror library will allow. Let me know if this helps

**Comment by scniro** [comment]
@TheMegaTB I tested this thouroughly and everything is working as expected, both automatically and manually via `showHint`. I started by looking at the [codemirror autocomplete demo](https://codemirror.net/demo/complete.html) and ensured my component had both the same options _and_ the required resources. For me, this looked as such...

```scss
// scss
@import '../../node_modules/codemirror/addon/hint/show-hint.css';
```


```jsx
require('codemirror/addon/hint/show-hint');
require('codemirror/addon/hint/javascript-hint');

<CodeMirror
  options={{
    extraKeys: {'Ctrl-Space': 'autocomplete'},
    mode: {name: 'javascript', globalVars: true}
  }}
  editorDidMount={(editor) => {
    window.editor = editor; // to test manually calling `showHint`
  }}
/>
```

Then hitting `Ctrl-Space` just like the demo, I get the auto complete menu to show just fine. Likewise, calling `editor.showHint` does the same. I am closing this issue out as I did not encounter any unexpected difficulties along the way. Please reopen if you can add any more detail for your particular usage.

**Comment by vimalchandhru** [comment]
Is there any way to use registerHelper to use own autocompletion menu? @scniro
