### ISSUE TITLE
Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by Sjoerrdd** [scniro/react-codemirror2#44]
Hi,
I'm getting the following error when I type in codemirror: `Cannot read property 'value' of undefined`
My code:

` <CodeMirror onChange={(event) => this.updateInput('paste', event.target.value)} value={this.state.paste} className="w-full flex" options={options} /> `

and the updateInput function: 

updateInput(field, value) {
  this.setState({ [field]: value });
}  
Normal input works, but codemirror doesn't

**Comment by appli456** [comment]
Did you import Controlled component?
If you import the component, you'd better move the setState function to the onBeforeChange (codemirror props).

**Comment by scniro** [comment]
@Sjoerrdd as @appli456 has mentioned you are needing to bind your event to `onBeforeChange` as the [docs show for controlled](https://github.com/scniro/react-codemirror2#controlled-usage). I'm going to close this out as it seems like a simple overlook in usage. Please re-open should you not be able to resolve this on your own. @appli456 thanks for the quick input on this as well!

**Comment by Sjoerrdd** [comment]
It has been solved, thanks :)
