### ISSUE TITLE
codemirror lib size

### ISSUE THREAD

**Issue by xralphack** [scniro/react-codemirror2#45]
The codemirror package is about 364 K, 
How do you handle this problem?

**Comment by scniro** [comment]
[codemirror](https://github.com/codemirror/CodeMirror) is a large project, with that comes size. In your case, I'm unsure what to do about it - but there are a few options. Look to minify and gzip your code. Then, look to lazy load this section of your app so the asset request is demand based. These are a couple of things that come to mind first. 

Keep in mind, If you have an in-browser editor, of course it's going to be sizable - especially if you start using the addons. Closing as this isn't a bug but more of a best practice question.
