### ISSUE TITLE
addLineClass

### ISSUE THREAD

**Issue by murtyjones** [scniro/react-codemirror2#46]
Is it possible to access [commands such as addLineClass](https://codemirror.net/doc/manual.html#commands) in react-codemirror2?

I was attempting to set the node like so:
```
<CodeMirror
  ref={ c => this.codeMirror = c }
/>
```
and add a class to a line like so:
```
this.codeMirror.addLineClass((nextState.errorLine - 1), 'errorLine')
```

No luck though.

**Comment by scniro** [comment]
No need to do this, just manipulate the instance! In this case, we'll persist it in `editorDidMount` (most a lot of callbacks in the docs pass this back). This keeps coming up - I think I'll add a "getting the instance" piece to the readme...

```jsx
constructor() {
  this.instance = null; // store here on `editorDidMount`
}

render() {
  <CodeMirror editorDidMount={(editor) => { this.instance = editor }}/>
}
```

then you can `this.instance.addLineClass((nextState.errorLine - 1), 'errorLine')`

**Comment by murtyjones** [comment]
Thanks! I also realized that I forgot an argument in addLineClass. In my case, it should've been:

```
this.codeMirror.addLineClass((nextState.errorLine - 1), 'wrap', 'errorLine')
```
rather than:
```
this.codeMirror.addLineClass((nextState.errorLine - 1), 'errorLine')
```

it's working now. Thanks again.
