### ISSUE TITLE
Can't change value from '' to 'foo'

### ISSUE THREAD

**Issue by fabiospampinato** [scniro/react-codemirror2#5]
[This](https://github.com/scniro/react-codemirror2/blob/master/src/react-codemirror2.jsx#L193) line looks wrong to me, why are we checking for `this.props.value`? By doing this I can't set a truthy value if the previous one was falsy.

**Comment by scniro** [comment]
Thanks for opening this up. Can you please explain a bit more? I don't fully understand your issue here. If there is a value prop, I set the value in the codemirror instance. I'll be happy to check this out but I just need a little more explanation.

**Comment by fabiospampinato** [comment]
The only thing that needs to be checked is if the current value and the next value are equal or not, which is what [hydrated](https://github.com/scniro/react-codemirror2/blob/master/src/react-codemirror2.jsx#L160) is all about.

The line I referenced to in the first post is also checking if the current value is truthy, which it shouldn't really care about. For instance if the current value is `''` (an empty string), then `if ( this.props.value )` will be `false`, and even if the new value is something like `'foo'`, `this.editor.setValue` won't be called.

**Comment by scniro** [comment]
@fabiospampinato makes sense. I'll get a fix up published tomorrow bright and early. Will post back here with an update. Thanks!

**Comment by scniro** [comment]
@fabiospampinato  [0.0.13](https://github.com/scniro/react-codemirror2/releases/tag/0.0.13) pushed up to npm with a fix for this seen [in this diff](https://github.com/scniro/react-codemirror2/commit/6b36e83e4e022d7e1c732b42bd056fbae373fcb4#diff-249949d0dc24c95a84a8cf818c31ff11). Please let me know if this resolves your issue. Thanks!

**Comment by fabiospampinato** [comment]
That fixes the issue, thanks!
