### ISSUE TITLE
Does not support matchbrackets

### ISSUE THREAD

**Issue by blittle** [scniro/react-codemirror2#50]
This project doesn't currently support the addon `matchbrackets` because CodeMirror has a bug that breaks the addon when multiple CodeMirror instances are active. `react-codemirror2` internally uses multiple instances: https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L389 and https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L393

I'm putting this issue here so that people are aware of the problem, though the issue I think lies in CodeMirror itself.

**Comment by scniro** [comment]
Nice, I see the PR was merged 👍. Since this was with codemirror itself I will close this out, but thank you for the awareness! Since the peer dep in the wrapper is `5.x`, we should get the fix as soon as the new lib package is available and no change needs to be made here.
