### ISSUE TITLE
Having issues with preventing edits

### ISSUE THREAD

**Issue by Flashwit** [scniro/react-codemirror2#52]
I don't know if this is something that's supposed to be supported but I thought I'd bring it up.
I'm using the Controlled version and checking for edits to some fields when `onBeforeChange` fires (this is editing JSON). If everything is all good, I set the `content` from `onBeforeChange` into my container components `state` and it gets passed back down to the `CodeMirror` component.

However, if the user has attempted to edit a 'locked' field, I show them a message and then just pass the previous `content` back into `CodeMirror`'s `value` prop.

While visually this appears to work, I believe there's an invisible internal state of the codemirror editor that isn't getting updated. This means what the user sees and the actual internal contents of `CodeMirror` become out of sync and things start breaking fairly quickly.

I've hacked around this for now by manually calling `initChange` and `setCursor` on a `CodeMirror` ref but it doesn't exactly feel great to do that.

Is there a proper way to do this sort of thing?

EDIT: I've been doing some more stuff and I think this issue could be more generic in that setting the `value` prop doesn't appear to to be able to CHANGE anything in the internal representation if it's in response to an `onBeforeChange` event because the `deferred` field is active internally causing `ReactMirror` to ignore the passed in `value`.

**Comment by Flashwit** [comment]
After even further work on this, I've used `onChange` instead to validate the user edits and replace them if necessary which is probably what I should've done in the first place.

I guess the only slightly annoying thing is that since it's now calling `initChange` itself it jumps the cursor to the bottom of the editing pane.

**Comment by scniro** [comment]
@Flashwit hey. thanks for opening this up. Unfortunately, I'm totally lost with what's going on here. I'd be happy to look into this with you if there is indeed an issue, but can you please start over and try and pin point what you believe the issue is? Please share with me your expected results and where the plugin is breaking.

**Comment by Flashwit** [comment]
Yeah, that got a bit long-winded.

To summarize, if you use `onChange` to change the contents of the editor (which I'm using to revert 'disallowed' edits) the cursor jumps to the bottom of the editing pane. It would be nice if the cursor kept its position.

**Comment by scniro** [comment]
@Flashwit Ah, gotcha! have you checked out [autoCursor](https://github.com/scniro/react-codemirror2#props)? Try setting `autocursor={false}` and let me know if this helps 😺

**Comment by Flashwit** [comment]
Ah yes, I probably have to do that and then set the cursor myself with the `cursor` prop. That should do.
