### ISSUE TITLE
How to access keyHandled event

### ISSUE THREAD

**Issue by lightninglu10** [scniro/react-codemirror2#55]
Hey guys, I'm trying to access a keyHandled event so I can preventDefault the original event.

I'm mapping a save command to the options like so: 

```
var codeMirrorOptions = {
      lineNumbers: true,
      tabSize: 2,
      theme: this.state.theme,
      mode: 'jsx',
      extraKeys: {
        "Cmd-S": this.codeKeyPress,
        "Ctrl-S": this.codeKeyPress,
      }
    }
```

but this.codeKeyPress is not getting an event passed to it, just the code mirror module.

**Comment by scniro** [comment]
Hm, which parameters are you inspecting in your function? I'm seeing a signature from [the docs](https://codemirror.net/doc/manual.html#event_keyHandled) as such

```
"keyHandled" (instance: CodeMirror, name: string, event: Event)
```

Are you not inspecting a third argument? I can't tell with your snippet as above. If there is indeed an issue here, perhaps I can add a custom handler for `keyHandled` and pass back what you need. Right now I'm doing nothing special for it. Let me know if this is helpful at all...

**Comment by scniro** [comment]
@lightninglu10, any more detail on this? Was my suggestion able to help you?

**Comment by lightninglu10** [comment]
Hey man, found a fix to the issue!

I set a ref on the codemirror object as this.codeMirror and then boom:

```
if (this.codeMirror) {
      var codeMirrorInstance = this.codeMirror.mirror;
      codeMirrorInstance.on('keyHandled', (cm, name, e) => {
        if (name === 'Cmd-S' || name === 'Ctrl-S') {
          e.preventDefault();
        }
      })
    }
```

**Comment by scniro** [comment]
That look nasty. Like I [mention in 56](https://github.com/scniro/react-codemirror2/issues/56) - getting the instance is likely the solution to both problems.
