### ISSUE TITLE
addLineClass not working

### ISSUE THREAD

**Issue by lightninglu10** [scniro/react-codemirror2#56]
In the docs, there's an api for addLineClass: http://codemirror.net/doc/manual.html#addLineClass

This works in the editor here: http://codemirror.net/demo/activeline.html

Open inspect element and type into the console: editor.addLineClass(10, 'wrap', 'newClassName'), and you'll see that line 10 gets the newClassName attached to the wrapper.

But when I try it with react-codemirror2, this doesn't happen. Is a prop being passed incorrectly as class instead of className somewhere?

**Comment by scniro** [comment]
`addLineClass` is a command. Please try [persisting the instance](https://mega.nz/#F!Fj5G2ALJ!vaQ1WiACCzQ8dot0WWlzcg). Anything you can do with the codemirror API, you can do manually.

**Comment by lightninglu10** [comment]
Hey @scniro, your link isn't working. Are you talking about persisting the instance [like this](https://github.com/scniro/react-codemirror2/issues/46)? 

So it looks like that works!

For anyone who runs into this issue as well, you should use the 

```
editorDidMount={(editor) => this.codeMirrorEditor = editor}
```

prop instead of trying to set a ref!
