### ISSUE TITLE
setGutterMarker not working: Uncaught TypeError: Failed to execute 'appendChild' 

### ISSUE THREAD

**Issue by lightninglu10** [scniro/react-codemirror2#57]
I'm trying to add an element to a gutter I defined, like so:

```
gutters: [
        'CodeMirror-linenumbers',
        'woop',
      ],
```

```
this.codeMirrorEditor.setGutterMarker(
        4, 'woop', <FontAwesomeIcon icon="question-circle" />
      );
```

Where `this.codeMirrorEditor` is the instance of CM. I get an error here though:

```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
```

And it looks like it may be because the instance of CM is not a react instance. Anyway around this other than creating a document element?

**Comment by scniro** [comment]
You can't pass a react component to codemirror and expect it to know what to do. Either manually render it beforehand, or pass a native DOM element. Looks like a font awesome icon. Not sure why one would use components for something as simple as `<i class='fa fa-question-circle' />`

Your last two issues were debugging your project. This one is no different. Please stop opening issues that aren't actual defects/absences from the codebase. Asking on [stackoverflow](https://stackoverflow.com/) might be helpful as well.

**Comment by lightninglu10** [comment]
These issues are related to debugging my projects, but they're applicable to many people who also may have the issue when using react-codemirror2. So if people search the repo here, they'll be able to find solutions to these issues.

It's not completely evident from first look that using your library wouldn't be able to handle React components.

But anyways, a solution is here:

```
      var parser = new DOMParser();
      var reactExcl = ReactDOMServer.renderToStaticMarkup(
        <FontAwesomeIcon icon="exclamation" color="#ff5370"/>
      );
      var excl = parser.parseFromString(reactExcl, "image/svg+xml").firstChild;
      var exclWrapper = document.createElement("div");
      exclWrapper.className = css(styles.exclamation);
      exclWrapper.appendChild(excl);
      this.codeMirrorEditor.setGutterMarker(
        4, 'woop', exclWrapper
      );
```

Basically you need to transition the react component into an HTML div element, and then pass it into codeMirror back into codeMirror.

**Comment by scniro** [comment]
> It's not completely evident from first look that using your library wouldn't be able to handle React components.

You don't need to look at it, it's obvious, calling the codemirror library directly, via the instance, passing a JSX react component as a parameter is going to blow up. Go pass jQuery a react component and see what happens. I don't really care to continue this argument.

Anyways, nobody is going to use that convoluted solution above, just pass the `<i>` and call it a day.
