### ISSUE TITLE
how to do code folding?

### ISSUE THREAD

**Issue by rileylnapier** [scniro/react-codemirror2#59]
hi, looking at codemirror docs it says:

```
  window.editor = CodeMirror.fromTextArea(te, {
    mode: "javascript",
    lineNumbers: true,
    lineWrapping: true,
    extraKeys: {"Ctrl-Q": function(cm){ cm.foldCode(cm.getCursor()); }},
    foldGutter: true,
    gutters: ["CodeMirror-linenumbers", "CodeMirror-foldgutter"]
  });
  editor.foldCode(CodeMirror.Pos(13, 0));
```

which i can pass the right options... but i'm not sure how to call `CodeMirror.Pos(13, 0)`

I tried with CodeMirror from 'react-codemirror' but it says Pos is not a function

**Comment by scniro** [comment]
Use the library, not the component to call that fn 

```
const CodeMirror = require(‘codemirror’);
```

You should be able to call `.Pos` now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rileylnapier** [comment]
i think its also an addon now that i look more into it.  another thread said you just need to do something like this?

```
import CodeMirror from 'react-codemirror';
import 'codemirror/lib/codemirror.css';
import 'codemirror/theme/oceanic-next.css';

if (typeof document !== 'undefined') {
  require('codemirror/mode/htmlmixed/htmlmixed');
  require('codemirror/mode/jsx/jsx');
  require('codemirror/addon/fold/foldcode');
}

```

???  have we verified?

**Comment by rileylnapier** [comment]
yeah, i add the plugin.  then with editorDidMount, the editor instance doesn't have `fold` on it. hmm

**Comment by scniro** [comment]
Try taking the `document` if statement out, and move your `require` statements above the imports?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rileylnapier** [comment]
i tried that too

**Comment by rileylnapier** [comment]
ok looks like i was just console.log(editor) and it didn't have editor.foldCode but if i console.log(editor.foldCode) the function is there.
