### ISSUE TITLE
how to use defineMode?

### ISSUE THREAD

**Issue by chocholand** [scniro/react-codemirror2#6]
I want to use my custom mode.

**Comment by scniro** [comment]
Hey thank you for opening this up. I have not played with custom modes before. I'll be happy to dig into this, but could you explain a bit more of what you're wanting to do? If you have any documentation or examples of this being done somewhere with the raw library I'll be happy to be sure it's supported. Thanks!

**Comment by chocholand** [comment]
I'm using custom mode. But in your code, it have to use internal codemirror instance.
When I use react-docemirror, I use mydefineModeFunction(codemirror) and I can pass codemirror to Codemirror with codeMirrorInstance.

**Comment by scniro** [comment]
@chocholand hey I wanted to quickly follow up with you while this topic is still fresh. Were you able to try out the change? I'd like to ensure this is resolved for you so please share your findings when you can. I hope to close this issue soon. Thanks!
