### ISSUE TITLE
[codemirror + redux-form] cursor goes to the end after validation

### ISSUE THREAD

**Issue by euZebe** [scniro/react-codemirror2#60]
I use an UnControlled from react-codemirror2 in a form which is managed by redux-form.

in MyForm component: 
```
<form className={styles.form} onSubmit={handleSubmit}>
  <Field
    name="html"
    component={CodeMirrorField}
  />
  //...
</form>
```
which I connect to redux and to the form validation callback as follows:
```
reduxForm({
  validate,
})(MyForm);
```
CodeMirrorField is rendered as follows:
```
<CodeMirror
  value={this.props.input.value}
  options={codeMirrorOptions}
  onChange={this.props.onChange}
/>
```
this.props.onChange is injected by redux-form, and is called whenever something is typed in codemirror, which induces a rerender of CodeMirrorField. Till there, nothing suprising.
But this rerender makes codemirror resetting cursor position to the very end of the field. 
And calling onChange callback another time.

Does anyone have any idea why the cursor is moved to the end, and why onChange is called again after rerender ? 
Should I use codemirror or react-codemirror2 differently ?

Note: the "funny" thing is that with react-codemirror, I had not the problem.

**Comment by scniro** [comment]
@euZebe I'd recommend looking into [`autoCursor` and `autoScroll`](https://github.com/scniro/react-codemirror2#props) which addresses this exact issue. There are also a few issues already closed out that ask similar. Please don't go back to react-codemirror, lol.

**Comment by euZebe** [comment]
autoScroll has no link with my cursor position problem. 
On the other hand, autoCursor doesn't work for my problem.
I implemented what I consider a hook:
```
<CodeMirror
  value={this.props.input.value}
  options={codeMirrorOptions}
  onChange={this.handleOnChange}
  cursor={this.state.currentPosition}
/>
```
and in the handleOnChange, I memoize the the cursor position so that I can restore it on render.

**Comment by VadSiam** [comment]
I have solved this : 
1. use `import {Controlled as CodeMirror} from 'react-codemirror2'`
2. inside redux-form did like this
`<CodeMirror
      {...props.input} // from redux-form input props
      onChange={() => {}} // onChange do nothing
      onBeforeChange={(editor, data, value) => !!props.input && props.input.onChange(value)}
      onBlur={(editor, data, value) => !!props.input && props.input.onBlur(value)}
      {...props}
    />`
