### ISSUE TITLE
Content Name Parameter

### ISSUE THREAD

**Issue by alauper** [scniro/react-codemirror2#64]
Hey Scniro, awesome library and great job maintaining it!

I have a basic question - I have the component working - my content field is javascript colorized accordingly. But when I submit my form, I don't see the content being passed as a parameter.  So I'm a little confused.  I'm expecting something similar to 

parameters: { active: true, **content: "var i = 1;\nvar j = 2;"**, name="John Doe" }

I've tried using uncontrolled and controlled approaches.

Example 

    import React, { Component } from 'react';
    import {UnControlled as CodeMirror} from 'react-codemirror2'

    require('codemirror/lib/codemirror.css');
    require('codemirror/theme/neat.css');
    require('codemirror/mode/xml/xml.js');
    require('codemirror/mode/javascript/javascript.js');

    ....

    <div style={{ border: '1px solid #cccccc', width: '90%' }}>
        <CodeMirror name="content" source="content" value='var i = 1;'
          options={{ extraKeys: { 'Ctrl-Space': 'autocomplete' }, lineNumbers: true,
          lineWrapping: true, mode: { name: 'javascript', globalVars: true }, theme: 'neat' }}
          onChange={(editor, data, value) => {}}
        />
    </div>

**Comment by scniro** [comment]
Hey @alauper thanks for opening this up. I've read over your issue a few times and unfortunately I'm struggling to grasp what the core issue could be. If you could, can you please start over and explain the situation as best you can. 

I looks like you're struggling with a form submission, in which case I assume `value` needs to be persisted somewhere *before* that submit. Anyways, I'll be happy to help, just need a little more info.

**Comment by scniro** [comment]
@alauper closing for now as I need more clarification on this. Please reopen should you have more detail to share.
