### ISSUE TITLE
Cannot read 'length' of undefined at `changeEnd`

### ISSUE THREAD

**Issue by njtrettel** [scniro/react-codemirror2#65]
## Setup
I've got a page with multiple `CodeMirror` instances that are all wrapped in a `redux-form` `Field`. I'm using the `Controlled` version so I can just call the redux form change handler and prevent codemirror changes:
```javascript
<CodeMirror
  className={dataClasses}
  options={{
    mode: 'python',
    lineNumbers: true
  }}
  onBeforeChange={(editor, data, value) => {
    this.props.input.onChange(value);
  }}
  {..._.omit(this.props.input, 'onChange')}
/>
```
I'm assuming my problem is coming from my usage with redux-form.

## Behavior
My problem occurs when I try to blur the editor, either by clicking directly on a different editor box or by just clicking off. The cursor remains in the editor I'm clicking off of and I get an error:
![codemirrorerror](https://user-images.githubusercontent.com/10906046/37361894-53556044-26ca-11e8-9083-d26baeb43c38.png)
Then, when clicking on a new editor, the previous cursor still remains on the old editor, and I get a cursor on the new editor as well. _I attempted to get a screenshot of this but when I open the screenshot program it finally blurs and the cursors disappear :sigh:_
So it seems like it won't blur because of the uncaught error.

I dug through a bit of those lines in the error but got stuck. To me it looks like it is having trouble recognizing no changes; it shouldn't go through the `makeChange` process when blurring because there are no changes.
EDIT: Removed now irrelevant screenshot for cleanliness

**Comment by dachinat** [comment]
Can you try adding 
```
onBlur={(editor, data, value) => {
}}
```
to `<CodeMirror />`?

**Comment by njtrettel** [comment]
Added `onBlur={() => console.log('onBlur')}`.

No log, it's breaking before it blurs. This explains why the cursor remains after clicking away.

**Comment by njtrettel** [comment]
Looked at it some more and I think that first bit of code is fine, shouldn't return early there. But a little later on it gets to here:
![changeend](https://user-images.githubusercontent.com/10906046/37406348-517f1352-276d-11e8-8816-c4998d30ee5b.png)

When I make a real change, `change.text` is an array:
![textarray](https://user-images.githubusercontent.com/10906046/37406398-739bf2b6-276d-11e8-901d-e02749a66634.png)
When I click off it is a CodeMirror object?
![textobject](https://user-images.githubusercontent.com/10906046/37406438-8d138e3e-276d-11e8-9dd3-01a03631bcb5.png)

**Comment by njtrettel** [comment]
I confirmed this is only happening in `redux-form` wrapped components

**Comment by scniro** [comment]
hey @njtrettel. Thanks for opening this up and sharing a lot of details. I'm just getting to looking at this now and there appears to be a lot to digest here. At this point, are you suspicious of a problem with this lib or how side effects of redux-form are impacting it? I have not had much experience with redux-form. Is focusing within the form trying to set a new `value`, or something perhaps?

**Comment by njtrettel** [comment]
hey @scniro, thanks for the reply. Sorry about the mess, I edited the original post to remove the screenshotted block of code because further investigation showed that was for sure not the problem. 

As far as where I think the problem is, I think it is how `redux-form` impacts the CodeMirror. I doubt the solution is a change in this library, but I think this is the best place for me to figure it out. 
When using the `Controlled` version with `redux-form` (haven't touched uncontrolled), clicking away triggers a change. 

When you mess with (i.e, touch, change, blur, etc) a field in redux-form, that component's props change, however, the `value` prop (which I am passing through) does not change.
Could it have something to do with changing unnecessary props such as `dirty`, `pristine` (passed through via `..._.omit(this.props.input, 'onChange')`)?

**Comment by njtrettel** [comment]
Oh... the props was the problem. I didn't realize that the redux form props in `this.props.input`:
```javascript
{..._.omit(this.props.input, 'onChange')}
```
included an `onBlur` already. So of course when I gave it an `onBlur` myself, the above ^^ line overwrote it.
An overlook on my part.

So the solution is to pick out the value explicitly instead of omit:
```javascript
<CodeMirror
  className={dataClasses}
  options={{
    mode: 'python',
    lineNumbers: true
  }}
  onBeforeChange={(editor, data, value) => value && this.props.input.onChange(value)}
  /* HERE: pick out only the value. and might as well get name. */
  {..._.pick(this.props.input, ['value', 'name'])}
/>
```

Just a misuse on my part, but at least worth noting. Maybe `redux-form`'s `onBlur` was returning something that caused CodeMirror to go through the `makeChange` process?

**Comment by scniro** [comment]
@njtrettel Man, I'm sorry to have witnessed the painful looking rabbit hole you went down to squash this! I'm glad you were able to come out the other end alive 😄 This was definitely a learning experience for me, with seeing how redux-form cooperates with other components, so I really appreciate how thorough you were from top to bottom. I'll be thinking on what could be triggering that `makeChange` event and I'll remember to post back here should I stumble across it. Thanks for using react-codemirror2 and feel free to open up issues here should any more surface.
