### ISSUE TITLE
Coloration issue with codemirror 5.29.0

### ISSUE THREAD

**Issue by Jerskouille** [scniro/react-codemirror2#7]
Hi there,

First, thanks for taking over maintenance of `react-codemirror`.
This is hugely needed and I'm found of the fact that people in the community take this over.

I've been using `react-codemirror2` for a while, and when updating to `codemirror@5.29.0`, the coloration stopped working.

Reproduction repo: https://github.com/Jerskouille/repro-codemirror-issue/ (notice the `doesnt branch`).
- First pull master, run `yarn && yarn start`, and you'll see that it works fine
- Then `git checkout doesnt && rm -rf node_modules && yarn && yarn start` and you should not see syntax coloration anymore

In case this matters, I'm using `node 8.4.0`.

I've tried to reproduce on a CodeSandbox instance, but it doesn't fail there.

**Comment by scniro** [comment]
@Jerskouille thank you for opening this up and being very detailed! I cloned down your example and indeed am not seeing any of the tokenization for the theme. Interesting, let me dig into this a bit later on and I'll keep you posted with my findings

**Comment by scniro** [comment]
@Jerskouille ah, looks like a minor syntax error on your end. Instead of passing a raw string as an HTML attribute, ensure you're passing it via the JSX object syntax. Check out the following...
```jsx
<CodeMirror
  value="(function a () { return 'test'; })"
```
needs to be
```jsx
<CodeMirror
  value={"(function a () { return 'test'; })"}
```

notice the `{ }`

**Comment by Jerskouille** [comment]
I've just force pushed the two branches to change this, but it doesn't change the issue.
Did you remove the `node_modules` folder when trying out the change?

![image](https://user-images.githubusercontent.com/5095856/29868842-dc6e4442-8d80-11e7-8edf-30872e25021b.png)

**Comment by scniro** [comment]
@Jerskouille weird, I just tried wiping everything and re-cloning indeed reproduces the issue again. I think I was playing with versioning and perhaps I only thought I found the fix. It actually appears that the syntax is okay...

So, I released [0.0.14](https://github.com/scniro/react-codemirror2/releases/tag/0.0.14) on npm which includes [CodeMirror 5.29.0](https://github.com/codemirror/CodeMirror/releases/tag/5.29.0) as the core dependency. This appears to fix the issue on my end alltogether.

Question - why are you wanting to include CodeMirror along with react-codemirror2 as independent deps? react-codemirror2 should be enough for you.

**Comment by Jerskouille** [comment]
Thank you for this!

You are completely right though, I should simply have added `react-codemirror2` and not `codemirror` too.
The reason I did that was because of the `require`s needed for the modes. When seeing it, I thought that it was needed as a direct dependency.

**Comment by Jerskouille** [comment]
So actually, this seems to be a best practice.
`eslint` is complaining in my project now that I've removed the dependency.

See https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md .

**Comment by scniro** [comment]
Hm interesting. I'm not a huge linter as it just seems to irritate me more so than provide any benefit. I see you can [disable this](https://stackoverflow.com/a/45841939/1464112) - but I totally understand if you didn't wish to do so I'm a bit at a loss for a solution here - any suggestions?
