### ISSUE TITLE
styles not affected Need Help

### ISSUE THREAD

**Issue by vimalchandhru** [scniro/react-codemirror2#70]
```
import React from "react";
import PropTypes from "prop-types";
require('codemirror/lib/codemirror.css');
require('codemirror/theme/material.css');
require('codemirror/theme/neat.css');
require('codemirror/mode/xml/xml.js');
require('codemirror/mode/javascript/javascript.js');

import {UnControlled as CodeMirror} from 'react-codemirror2';


export default class App extends React.Component {
  constructor(props) {
    super(props);
}



  render() {
    return(
      <CodeMirror
  value={"var a=10;"}
  options={{theme:"material",mode:"javascript"}}
/>
    )
  }
}



App.propTypes = {


};
App.defaultProps = {

};
App.docs = {
};

```

This is my code and this is my result
<img width="958" alt="screenshot 253" src="https://user-images.githubusercontent.com/10485165/37636862-7661f10a-2c2a-11e8-9776-d638127743cc.png">

why css are not downloading?
is there any mistakes in my code? @scniro

**Comment by scniro** [comment]
@vimalchandhru Have you doble checked your [webpack css loader](https://github.com/webpack-contrib/css-loader#usage)? I suspect you're not loading the style sheets correctly. Otherwise this looks fine.

**Comment by scniro** [comment]
@vimalchandhru closing for now as I suspect your development setup could be the culprit here and not the component itself. Please reopen if you are able to provide any additional detail.
