### ISSUE TITLE
Feature Request: resizable

### ISSUE THREAD

**Issue by njtrettel** [scniro/react-codemirror2#71]
Okay bear with me here...

I managed to get a resize-able CodeMirror working, but it's pretty hacky and doesn't look right in the end.

I'm aware of the provided function to programmatically change the size of the box but this isn't quite what I'm looking for. 
The goal is to have a resizable editor like a `textarea`, which sets the inline `height` and `width` properties. 

Since CodeMirror doesn't provide a way to resize in ^^this manner, I must workaround. Essentially it boils down to whose scrollbars I want to use: CodeMirror's or the parent's `overflow: auto/scroll`.

## Using CodeMirror scrollbars
No matter how I do this using the CodeMirror scrollbars, the resize grabber will not overlap with the scrollbar. CodeMirror stays in the foreground, on top of the resize grabber, and therefore I cannot click/drag it. I can set the scrollbar filler CSS to `display: none`, but this makes it _visible_ but not _clickable_. Here are some examples:

> _the CodeMirror scrollbar filler is in front of the grabber. clicking the grabber actually scrolls down. `z-index` did nothing (that makes sense though, the grabber is not an element). Another resulting problem is you can see right through to the text._
![codemirror4](https://user-images.githubusercontent.com/10906046/37785155-cc95f606-2dcf-11e8-924a-065f5960d34d.png)

> _this one is the closest I've gotten, but you can see I had to add padding in order to allow the grabber to appear. making the scrollbar hidden does nothing this time, probably something else getting in the way?_
![codemirror3](https://user-images.githubusercontent.com/10906046/37783342-a32e283c-2dcb-11e8-8dd1-d98694a39e87.png)

## Using parent's scrollbars
Now, I try to use the parent container's scrollbars by setting the `scrollbarStyle: 'null'` option. This works for vertical scrolling, but the width of the CodeMirror never actually overflows (because the "big" component is `.CodeMirror-sizer`) so I never get the horizontal scrollbar. Like so:
>you can see the height is overflowed, but the width stays the same.
![codemirroroverflow](https://user-images.githubusercontent.com/10906046/37787317-0ca6ac72-2dd5-11e8-864a-3c7d51da70d9.png)

I think the only way for this to work cleanly is if a child in the CodeMirror component had the resizable property, and it wouldn't be necessary to click/drag the grabber "under" the CodeMirror. This probably stems from what looks like custom scrollbars (`.vscrollbar` & `.hscrollbar`). 

I understand I could implement the grabber, manage click/drag listeners and a state, and programmatically set the height myself. But this seems like a pretty wide use-case that would be useful if built-in.

**Comment by scniro** [comment]
@njtrettel hey! Okay, so, I think the ask is to provide a `<CodeMirror resizable={true}/>` component. Is that the case? If so, I can take the research you've already shared here and implement this into a single prop and abstract away all this gritty resizing stuff.

**Comment by scniro** [comment]
@njtrettel you got it! I'll try my best to focus on this over the weekend and I'll post back here with my findings 😎

**Comment by scniro** [comment]
@njtrettel Hey I haven't forgotten about this. Ended up a littler busier this weekend than I thought. However I did look into some options and came across [bokuweb/re-resizable](https://github.com/bokuweb/re-resizable) and it surprisingly worked out of the box for me. 

I'm considering adding as a dep to the repository and simply return a wrapped `</Resizable>` component if `resizable={true}` is passed. However, if it indeed can be dropped in like that I might not have to do anything but instead include examples using that lib. I'll need to actually see how the editor responds in certain cases and examine whether I'll need to communicate props between the two. If there is some involvement there I'll likely bake this in.

I was also leaning towards using the codemirror scrollbars and *not* the parent element's for the sake of folks who will want to apply themes to their scrollbars. Thoughts?

**Comment by njtrettel** [comment]
@scniro that package looks awesome, thanks for looking into that. 

I think communication between the two's props are essential because people will certainly want to use the `Resizable` props they provide. In my case, I don't want the ability to resize horizontally so I need their `enable` prop. Definitely in favor of using codemirror scrollbars. Based on what I've seen that looks less complicated anyway, not to mention the custom styling. 

I'm going to play around with wrapping my `CodeMirror` with `Resizable` as well and let you know if I see anything weird.

**Comment by njtrettel** [comment]
@scniro so it works really well, the only thing I see that is a little annoying in my case that could be abstracted away is filling the height. Since the code box is in `div.resizable__container` > `div.react-codemirror2` > `div.CodeMirror`, I have to pass the height through from the `Resizable` to the `CodeMirror`:

*_excluding `min-height` stuff, which should be required for resizable every time in my mind_*
```css
.react-codemirror2 {
  height: 100%;
}
.CodeMirror {
  height: 100% !important;
}
```

Can't think of anyway to do this as a one-line CSS solution, both of those^^ children need 100% height.

**Comment by scniro** [comment]
@njtrettel did you have to establish some prop transacting between the two or did it just respond as you'd expect? I'm trying to gauge whether it's worth pulling in the dep or just throwing this usage in the readme

**Comment by njtrettel** [comment]
it just responded as expected. I just have to set the height with CSS like above. 

The more I think about it, i think it might be best to leave it out to leave all of the customization of Resizable. ultimately up to you.

**Comment by scniro** [comment]
@njtrettel yea that was my initial finding as well. If it's a straightforward drop in, I'm leaning towards leaving it out and just include a detailed example in the readme. I'll take what you shared so far, confirm everything on my end, and add to the readme. I hope that will suffice! Thanks for the collaboration on this one.

**Comment by njtrettel** [comment]
@scniro no, thank you for keeping up with this project! this solution definitely works for me.

**Comment by scniro** [comment]
Added a [FAQ section](https://github.com/scniro/react-codemirror2#faq) to the readme where I mention this. Helpfully it'll help others! Closing for now, please repoen should you have any other concerns

**Comment by mb21** [comment]
@scniro I found resizing works also really well without an other React component. See e.g. https://codemirror.net/demo/resize.html

Or for my needs it was `options={ {lineWrapping: true} }` and then:

```
div.CodeMirror {
  height: 100vh;
}

/* Make editor resize to fit its content
 * see also https://codemirror.net/doc/manual.html#styling
 */
.CodeMirror-scroll {
  overflow-x: auto;
  overflow-y: hidden;
}
```

**Comment by chayanbaner** [comment]
can also do this on editorDidMount, eg:
```js
<CodeMirror
                        value={editorValue}
                        options={options}
                        editorDidMount ={(editor) =>{
                            editor.setSize("", "100%");
                        }}
                        onBeforeChange={(editor, data, value) => {
                            
                        }}
                        onChange={(editor, data, value) => {
                        }}
                    />
```
 **editorDidMount ={(editor) =>{
                            editor.setSize("", "100%");
                        }}**
