### ISSUE TITLE
Format default value

### ISSUE THREAD

**Issue by GloriaCHL** [scniro/react-codemirror2#72]
Hi, I set json data to the component value after use JSON.stringify (because the value prop type is  string), it just looks like this:
![default](https://user-images.githubusercontent.com/10557315/38008191-f6704a80-327f-11e8-815a-20196b8357f2.png)
How can I format json data in the component? thanks

**Comment by njtrettel** [comment]
You're looking for a "pretty print". it's built in to `JSON.stringify` as the third (`space`) parameter (ignore the second):

```javascript
const obj = {a: 1, b: { c: 3, d: 4 } };

JSON.stringify(obj, null, 2);
/* result:
{
  a: 1,
  b: {
    c: 3,
    d: 4
  }
}
*/
```

^^ that's probably all you'll need but you can see the rest of the options for the `space` argument here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify

**Comment by scniro** [comment]
As @njtrettel pointed out, you can format your input before specifying. Closing for now, please repoen should have have any more difficulty with this.
