### ISSUE TITLE
paste event

### ISSUE THREAD

**Issue by TigerBill2016** [scniro/react-codemirror2#74]
i should paste files into codemirror, but cant trigger paste event, thanks

**Comment by scniro** [comment]
@TigerBill2016 nice, this seems to be a new codemirror feature. I see a handful of new [DOM events](https://codemirror.net/doc/manual.html#events) that I can add. I'll keep you posted when a new release with this is cut 👍

**Comment by scniro** [comment]
fixed with the [4.3.0 release](https://github.com/scniro/react-codemirror2/releases/tag/4.3.0)
