### ISSUE TITLE
Object.assign doesn't work by default in Internet Explorer

### ISSUE THREAD

**Issue by anandsainath** [scniro/react-codemirror2#76]
We use **Object.assign** in the following line - https://github.com/scniro/react-codemirror2/blob/3250f5833f48e65a1b560dc3059f0ce4ed0771fd/src/index.tsx#L616

Unfortunately, Internet Explorer doesn't have a definition for the same. And its very difficult to override object.assign from an external module :(

Can we depend on an external library (like core-js) to get the definition for assign and use that instead?

**Comment by scniro** [comment]
@anandsainath Are you using webpack/babel? I suppose I can add a polyfill, but it feels so... gross. I'll keep you posted with if I add anything but I definitely think you can handle this through a bundler.

**Comment by scniro** [comment]
fixed with the [4.3.0 release](https://github.com/scniro/react-codemirror2/releases/tag/4.3.0)

**Comment by anandsainath** [comment]
@scniro Thank you! :)
