### ISSUE TITLE
[Bug] onTouchStart property required

### ISSUE THREAD

**Issue by Mamoru1234** [scniro/react-codemirror2#78]
Actual behavior:
According [to this line](https://github.com/scniro/react-codemirror2/blob/master/src/index.tsx#L83) onTouchStart is required property.
Expected behavior:
onTouchStart should be optional.

**Comment by scniro** [comment]
@Mamoru1234 dang, good catch. Yep, `onTouchStart` needs to be `onTouchStart?` I'll get a fix in this evening please just no-op it for now if you can get by

**Comment by scniro** [comment]
@Mamoru1234 I don't enforce any of the type checking for the tests. I probably should after seeing this (lol). PR merged, will bump a publish in a few moment

**Comment by scniro** [comment]
@Mamoru1234 fixed with the [5.0.1 release](https://github.com/scniro/react-codemirror2/releases/tag/5.0.1)
