### ISSUE TITLE
showHint not working....was available in react-codemirror

### ISSUE THREAD

**Issue by stepwisetraders** [scniro/react-codemirror2#80]
Thanks for the updated component!
Wondering how I can re-implement the showing of hints (addon/hint/show-hint)??

**Comment by stepwisetraders** [comment]
Sorry...realized I was using the old way of calling showHint....it's working :)

**Comment by michaelmior** [comment]
@stepwisetraders Could you show what wasn't working and what you changed? I may be running into the same problem.
