### ISSUE TITLE
Redefine the size of react-codemirror2

### ISSUE THREAD

**Issue by Gfast2** [scniro/react-codemirror2#84]
Hi guys,

Thanks for your awesome stuff! 👍 

Right now I'm working on a page that using [flex box](https://css-tricks.com/snippets/css/a-guide-to-flexbox/). I'm expirencing a small issue: The size of `react-codemirror2` can not be resized. 🔽 the css class I'm using has made correct size for codemirror, but codemirror won't take all the place it should use. I think [_**this**_](https://stackoverflow.com/questions/12349529/change-height-and-width-of-textarea-in-codemirror?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) is somehow about this topic, but I can't use it.

Is there some _**geniue**_ way to approach?

Cheers 

Su

**Comment by Gfast2** [comment]
![editor](https://user-images.githubusercontent.com/2803903/39574602-179e6948-4ed8-11e8-8e41-e79e0d595ff1.png)
The black parts is the size what `react-codemirror2` still not taken. This part I've specified as `className`. Finally I wanna extend the size of codemirror to take over all places it should take.

**Comment by scniro** [comment]
> Bulls Shits.

@Gfast2 🤣 thanks for the morning lol. Anyways, I think we can get you squared away here. Before I did into this too much, take a look at #58 - you may find the solution there with basic styling. Let me know if that helps at all and we'll go from there!

**Comment by Gfast2** [comment]
Hi @scniro,

Thanks for you suggestion and crazy fast reaction! 👍 ⚡️ 

I've tried you solution headlessly. I didn't works out of the box. Because I did this layout many days before, I do not have the feeling where should be the problem.

When I got anychance to fix this issue, I'll come back. But I won't do it instantly.

BTW: Should I close this issue, or allow me for some days to try out the possible solution here?

**Comment by scniro** [comment]
@Gfast2 feel free to keep this open and just report back with your findings - I'd like to see this get resolved for you 😸

**Comment by Gfast2** [comment]
Hi @scniro 

All right. Let us see what I will get. 🌻

**Comment by scniro** [comment]
@Gfast2 any updates? Hoping to get this closed out soon. Let me know, thanks!

**Comment by Gfast2** [comment]
Hi @scniro,

I did investigate some efforts these days. But it still not fit my need.

I close it at first. If I did really got somewhere. I will be back again. 🌻 

Cheers

Su
