### ISSUE TITLE
After use webpack to build, the style of codemirror has some wrong

### ISSUE THREAD

**Issue by solayao** [scniro/react-codemirror2#85]
Hi,
when i use the react-codemirror2 in webpack-dev-server, it worked like this
![image](https://user-images.githubusercontent.com/14294893/40160314-b27cd94c-59df-11e8-8bc9-b538e1945599.png)
however, after i built the project, it worked like this
![image](https://user-images.githubusercontent.com/14294893/40160396-2028697a-59e0-11e8-927c-ae4a534d8266.png)
and i found that change two style it normal work again
![image](https://user-images.githubusercontent.com/14294893/40160578-ae8cca9e-59e0-11e8-98d6-973b9cc4f4dd.png)
but i don't know how to fix the problem at all

**Comment by scniro** [comment]
@solayao Unfortunately I am going to close this issue as it's definitiely more related to [webpack](https://webpack.js.org/concepts/) and your development setup. react-codemirror2 has no special instruction for bundling with webpack so long as you properly [include the resources](https://github.com/scniro/react-codemirror2#requiring-codemirror-resources). I'd suggest composing this into a question on https://stackoverflow.com/ if you continue to struggle 👍

**Comment by qhxin** [comment]
it's really a BUG in webpack-dev-server !
