### ISSUE TITLE
onChange event firing twice

### ISSUE THREAD

**Issue by rolandgnm** [scniro/react-codemirror2#87]
Hello guys, I've been working with this module for a few weeks but only today I noticed my `onChange` handler has been called twice. I imagine it has something to do with event bubbling but  the onChange function signature does not include the event so I can run `event.preventDefault()`. Here is my is my code: 

```javascript
const Editor = ({ value, onUpdate }) => {
  const handleChange = (editor, data, val) => {
    onUpdate(val)
  }

  return (<CodeMirror
    value={value}
    onChange={handleChange}
    options={{
      mode: 'javascript',
      theme: 'lesser-dark',
      lineNumbers: true,
    }}
    autoCursor={false}
  />
  )
}
```

**Comment by rolandgnm** [comment]
Thanks @scniro for your response, I haven't noticed your example was printing on console. That would be enough to guarantee the error is in my setup. I'll check my component structure and come back with the solution for my case or some more details if I get stuck.

**Comment by scniro** [comment]
@rolandgnm just keep me posted with your findings! We'll get this squared away for ya 😺

**Comment by rolandgnm** [comment]
Thanks @scniro, my error was actually on my side. Assessing the example closer I found out I've chosen wrong combination for component (un/controlled) and change handler. Now it's pretty much like this, and running properly: 

```js
<Controlled
      value={value}
      onBeforeChange={handleChange}    
/>
```
