### ISSUE TITLE
Feature Request: Adding a contributing guide

### ISSUE THREAD

**Issue by anandsainath** [scniro/react-codemirror2#90]
It would be awesome if there was a contributing guide/readme that detailed the steps needed to create a pull request - especially around generating the necessary files and may be the commands to run them.

I'll be happy to automate that in anyway possible :)

**Comment by scniro** [comment]
@anandsainath Agreed! I'm happy folks actually want to contribute so hopefully [this bit](https://github.com/scniro/react-codemirror2#contributing) makes it a little more straight forward. Can you give a look and let me know if this clarifies things?

**Comment by anandsainath** [comment]
Thanks @scniro! That works!
