### ISSUE TITLE
onSelect features help

### ISSUE THREAD

**Issue by owcc** [scniro/react-codemirror2#91]
`beforeSelectionChange` can not get current *selection*, how to get current  *selection*(like `onSelectionChange` method)?

**Comment by owcc** [comment]
no, codemirror has no api for this:(  in my case, i need to know it when user select end so i can do something next...Oh, maybe add an *mouseup* event and then pick current selection from *doc.getSelection* can make it just work?  it will be nice if you  willing to do it so can be more elegant, anyway, thank you for your quick reply.

**Comment by scniro** [comment]
@owcc ahh I see where you're coming from now. I think your workaround will indeed work for you, though it may come with a gotcha. What if your user selects a range with the keyboard only? Let me chew on this for a little bit and I'll get back to you with a solution.

**Comment by owcc** [comment]
haha...poor english as me, In fact, users on my project use mouse more...
