### ISSUE TITLE
Support for renderLine event?

### ISSUE THREAD

**Issue by rgov** [scniro/react-codemirror2#98]
I want to be able to implement the functionality in the [indented wrapped line demo](https://github.com/codemirror/CodeMirror/blob/master/demo/indentwrap.html), which involves adding an event handler for the renderLine event. But this doesn't appear to be one of the ones exposed by `react-codemirror2`.

**Comment by scniro** [comment]
@rgov intersting, I must not have seen this one. Should be easy enough to add. I'll get this in, hopefully soon!

**Comment by scniro** [comment]
@rgov fixed with the [5.1.0](https://github.com/scniro/react-codemirror2/releases/tag/5.1.0) release!
